core/src/main/python/wlsdeploy/aliases/aliases.py, core/src/test/python/aliases_test.py
=> Added get_model_attribute_name for alias validation testing

core/src/main/antlr4/oracle/weblogic/deploy/yaml/Yaml.g4, core/src/test/python/variables_test.py, core/src/test/resources/variables-test.json, core/src/test/resources/variables-test.yaml, core/src/test/resources/variables.properties
Issue#69 - Allow ID to be specified as @@PROP:key@@. Fixes #69
=> Issue#69 - Allow ID to be specified as @@PROP:key@@. Fixes #69

README.md
Issue#79 - Use @@PROP:key@@ syntax for variable replacement. Fixes #79
=> Issue#79 - Use @@PROP:key@@ syntax for variable replacement. Fixes #79

core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/Partition.json, core/src/test/python/aliases_test.py
Fixed Partition.json so that now it has it's own ResourceManager subfolder, instead of using the "contains" list.  Fixes #39
=> Issue#39 partition alias json file update

core/src/main/java/oracle/weblogic/deploy/util/ProcessHandler.java, core/src/main/java/oracle/weblogic/deploy/util/ScriptRunner.java
Fixes #89 
This is an enhancement we discussed doing a while back. The default behavior is to not append.
=> Issue#89 add new execute script method to script runner.java

core/src/main/python/wlsdeploy/tool/discover/topology_discoverer.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
=> Added _get_nm_properties() and a resource message

core/src/main/python/wlsdeploy/tool/create/domain_creator.py
Restored disabled create logging. Fixes #99
=> issue#99 - Restored disabled create logging. Fixes #99

core/src/main/python/wlsdeploy/aliases/alias_entries.py, core/src/main/python/wlsdeploy/aliases/aliases.py, core/src/main/python/wlsdeploy/tool/create/creator.py, core/src/main/python/wlsdeploy/tool/util/alias_helper.py, core/src/main/python/wlsdeploy/tool/validate/validation_utils.py, core/src/main/python/wlsdeploy/tool/validate/validator.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, wercker.yml
=> Modifications to handle VERSION_INVALID folders being present in a model

core/src/main/python/wlsdeploy/tool/util/alias_helper.py, core/src/test/python/validation_test.py
Fixes #102 
Actually, a couple methods were missing and probably went unnoticed because Python isn't a compiled programming language. I added 4 unit tests to validation_test.py in order to combat this type of thing with print usage, in the future
=> Added missing alias_helper methods and some unit tests

core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/Server.json
Revise server aliases to correctly match paths. Fixes #110
=> Issue#110 - Revise server aliases to correctly match paths

core/src/main/java/oracle/weblogic/deploy/util/PyOrderedDict.java, core/src/test/python/collections_test.py
=> Issue#113 dict.update(py ordered dict) not working

core/src/test/python/validation_test.py
=> Commented out the testPrintUsageCLAEnforcement method, for now

README.md
=> Issue#127 - Add a description for the Update Domain Tool

samples/docker-domain/README.md
=> minor fixes

core/src/test/python/aliases_test.py
=> Issue #137 - Use explicit WLS version in unit test

core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/Server.json, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/ServerTemplate.json, core/src/test/python/aliases_test.py
=> Issue#132 correct single unpredictable folders

core/src/main/python/wlsdeploy/tool/validate/validator.py, core/src/main/python/wlsdeploy/util/model_context.py
=> Issue #140 - Check for token prefix before checking for relative paths

core/src/main/java/oracle/weblogic/deploy/logging/SummaryHandler.java, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Add weblogic deploy version to tool message summary header.
=> Add tool version to summary header in wrap up messages

core/pom.xml, installer/pom.xml, pom.xml
back to development snapshot version
=> Do release 14

core/src/main/python/wlsdeploy/tool/discover/common_resources_discoverer.py, core/src/main/python/wlsdeploy/tool/discover/topology_discoverer.py, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/JTA.json, core/src/test/python/aliases_test.py
Add JTA and PathService to Discover
=> Fix for JTA and PathService in JTA

core/src/main/python/wlsdeploy/tool/discover/discoverer.py, core/src/main/python/wlsdeploy/tool/discover/jms_resources_discoverer.py, core/src/main/python/wlsdeploy/util/wlst_helper.py, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/JMSSystemResource.json
Add check for null subdeployment name in group params
=> Wdt 50 groupparams

core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py
Fix issue #192 where the name of the app doesn't match the manifest causing the app not able to start
=> Versionapp fix

core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/JMSSystemResource.json
Additional changes for deploy and online discover of SAF imported destinations
=> JIRA WDT-50 Fix SAF imported destination discover and deploy issues

core/src/main/antlr4/oracle/weblogic/deploy/yaml/Yaml.g4
This should fix the slashed name issue
=> handle slash in name

core/src/test/python/alias_password_test.py
Test that the decrypted password is as expected.
=> Wdt 250 add a unit test for encrypted password

core/src/main/python/wlsdeploy/aliases/alias_jvmargs.py, core/src/test/python/alias_jvmargs_test.py
=> Issue #259 - Allow uppercase multipliers in size and other -X arguments

core/src/main/python/create.py, core/src/main/python/wlsdeploy/tool/create/atp_helper.py
fixed atp extract problem when domain_home is passed and use system property for oracle.jdbc.fanEnabled=false instead of OS env
=> fix the npe caused by another option - domain_home

core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/MailSession.json
Use get method for mail session properties with WLST online.
Tested with online update and online discover.
Fixes #328
=> Issue #328 - Use get method for mail session properties with WLST online

LICENSE.txt
Change the copyright date on WDT license (delivered in installer)
=> Change 2018 to 2019

core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/AdminConsole.json
Alias definition test found this.
Verified with create, discover.
=> Corrected minimum version for SSO logout URL

core/src/main/python/wlsdeploy/tool/discover/topology_discoverer.py
Correct method name for convert-path usage, fixes #338
=> Correct method name for convert-path usage

core/src/main/python/wlsdeploy/tool/create/domain_creator.py
add boot.properties to the security folder at the end of domain creation
=> Addbootproperties

installer/src/main/bin/createDomain.sh, installer/src/main/bin/deployApps.sh, installer/src/main/bin/discoverDomain.sh, installer/src/main/bin/encryptModel.sh, installer/src/main/bin/injectVariables.sh, installer/src/main/bin/updateDomain.sh, installer/src/main/bin/validateModel.sh
Replaced unix shell script string comparisons with -z (or -n) conditional tests
=> Convert error prone string comparisons to shell script conditional

core/src/main/java/oracle/weblogic/deploy/util/CLAUtils.java, core/src/main/python/encrypt.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Fix to avoid closing stdin stream when encrypt.sh is run in non-console mode.
=> Fix stdin entries to avoid closing stdin stream

core/src/main/python/validate.py
=> Issue #426 - Return warning or error exit codes if problems are found

core/src/main/java/oracle/weblogic/deploy/aliases/TypeUtils.java, core/src/test/java/oracle/weblogic/deploy/aliases/TypeUtilsTest.java
=> Issue #490 - Remove trailing L from long property values

core/src/main/python/wlsdeploy/tool/create/creator.py, core/src/main/python/wlsdeploy/tool/util/topology_helper.py, core/src/main/python/wlsdeploy/util/variables.py
Found a comparison for str in fields that also can be unicode.
Changed several dictionary searches that were done like list searches. Jython later not as friendly with those searches. I believe it references the underlying list that is a consolidation of all the changes done to the dictionary.
=> Properties in names and manipulation of dict

core/src/main/python/create.py, core/src/main/python/deploy.py, core/src/main/python/discover.py, core/src/main/python/update.py, core/src/main/python/validate.py, core/src/main/python/variable_inject.py, core/src/main/python/wlsdeploy/tool/util/model_context_helper.py, core/src/main/python/wlsdeploy/util/model_context.py
Create model context helper for consistent initialization of typedef
=> JIRA WDT-380 Set typedef correctly for deploy

core/src/main/python/wlsdeploy/tool/util/variable_injector.py
For discover, use the file name passed on variable_file argument
=> WDT#498-for-discover-use-variable-file-name

core/src/main/python/wlsdeploy/tool/validate/validation_utils.py, core/src/main/python/wlsdeploy/tool/validate/validator.py, core/src/main/python/wlsdeploy/util/variables.py, core/src/test/python/variables_test.py, core/src/test/resources/encryption-test-variables.yaml, core/src/test/resources/variables-test.json, core/src/test/resources/variables-test.yaml, system-test/src/test/java/oracle/weblogic/deploy/integration/ITWdt.java
This restored some broken validation code as well.
Jira WDT-377
=> Remove curly brace properties, allow @@PROP in lists

core/src/main/python/wlsdeploy/tool/discover/discoverer.py, core/src/main/python/wlsdeploy/tool/discover/topology_discoverer.py
Properly parse classpath, detokenize and correct path for comparison
=> Issue#379 classpath libraries adding oracle files to archive

core/src/main/java/oracle/weblogic/deploy/util/PyOrderedDict.java, core/src/main/python/wlsdeploy/util/variables.py
=> Fix ordered dictionary to completely delete keys; use delete in variable substitution

core/src/main/python/extract_resource.py, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/ServerTemplate.json
=> Create server template JTA migratable target with ${serverName} macro

core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py
=> Issue #552 Pass path parameter to WLST helper method

core/src/main/python/wlsdeploy/json/json_translator.py
=> Format strings in JSON lists with double-quotes

core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
JIRA-WDT-389
This scenario occurs when a domain type with extension/custom templates is created, and is not JRF (currently only RestrictedJRF).
=> Clarify RCU message, reduce level to FINER

core/src/main/python/extract_resource.py, core/src/main/python/variable_inject.py, installer/src/main/bin/extractDomainResource.cmd, installer/src/main/bin/extractDomainResource.sh, installer/src/main/bin/injectVariables.cmd, installer/src/main/bin/injectVariables.sh, installer/src/main/bin/shared.cmd, installer/src/main/bin/shared.sh
JIRA WDT-387, part 2
Refactor extractDomainResource and injectVariables to use shared functions.
=> Convert extractDomainResource and injectVariables to use Jython directly

README.md
Fixes #555 
The ENV token is not implemented
=> Add @@FILE token, factored out model tokens section

core/src/main/python/wlsdeploy/tool/util/topology_helper.py
=> Set JDBCSystemResource / JdbcResource / Name when creating placeholders

core/src/main/python/wlsdeploy/util/variables.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, core/src/test/python/variables_test.py
=> Implement environment variable lookup in model

README.md, core/src/main/python/validate.py, core/src/main/python/wlsdeploy/util/variables.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, core/src/test/python/variables_test.py, core/src/test/resources/secrets/my-secrets/secret2, core/src/test/resources/secrets/secret1
Internal Jira WDT-370
Add ENV token to README as well.
=> Implement SECRET token

core/src/main/python/wlsdeploy/util/variables.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, core/src/test/python/variables_test.py
=> Check for token syntax errors after substitutions

core/src/main/python/model_help.py, core/src/main/python/wlsdeploy/util/cla_utils.py, core/src/main/python/wlsdeploy/util/model_context.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, installer/src/main/bin/modelHelp.cmd, installer/src/main/bin/modelHelp.sh
```
modelHelp.sh -oracle_home /oracle topology:/Server
```
Internal JIRA WDT-388
=> Change command line to not require -path argument

installer/src/main/bin/modelHelp.sh
Just added some trailing quotation marks
=> Fixed usage errors

core/src/main/python/create.py, core/src/main/python/deploy.py, core/src/main/python/discover.py, core/src/main/python/update.py, core/src/main/python/wlsdeploy/util/cla_helper.py, installer/src/main/bin/createDomain.cmd, installer/src/main/bin/createDomain.sh, installer/src/main/bin/deployApps.cmd, installer/src/main/bin/deployApps.sh, installer/src/main/bin/discoverDomain.cmd, installer/src/main/bin/discoverDomain.sh, installer/src/main/bin/shared.cmd, installer/src/main/bin/shared.sh, installer/src/main/bin/updateDomain.cmd, installer/src/main/bin/updateDomain.sh
Modify .cmd and .sh UNIX scripts to use shared script.
Modify entry modules for create, update, deploy, discover to use common Jython code.
Internal Jira WDT-402
=> Refactor scripts to use shared code

core/src/main/python/compare_model.py, installer/src/main/bin/compareModel.cmd, installer/src/main/bin/compareModel.sh, site/compare.md
This renam all model_diff / modelDiff to compare model
=> fix model_diff names

core/src/main/java/oracle/weblogic/deploy/logging/SummaryHandler.java, core/src/test/python/compare_model_test.py, core/src/test/python/validation_test.py
Initialize summary handler for compareModel and validate unit tests.
Suppress stack traces in compare-model tests.
=> Fixes for compareModel unit tests

core/src/main/python/model_help.py, core/src/main/python/wlsdeploy/tool/modelhelp/model_help_printer.py, core/src/main/python/wlsdeploy/tool/modelhelp/model_help_utils.py, core/src/main/python/wlsdeploy/tool/modelhelp/model_sample_printer.py, core/src/main/python/wlsdeploy/util/cla_utils.py, core/src/main/python/wlsdeploy/util/model_context.py, core/src/test/python/wlsdeploy/tool/modelhelp/model_help_printer_test.py, installer/src/main/bin/modelHelp.cmd, installer/src/main/bin/modelHelp.sh
This creates a prototype model section that can that can be copied into a model.
Documentation will be a separate PR.
Internal JIRA WDT-320 (partial)
=> Add -model_sample option to modelHelp

site/samples/configured_cluster.md, site/samples/samples.md
No related code change, merge when ready
Internal JIRA WDT-407
=> Added sample model for configured cluster

core/src/main/python/compare_model.py
=> fix compare model to use lax validation

site/encrypt.md
Documentation that encrypt can take multiple models.
=> Document multiple models in Encrypt tool.

core/src/main/python/wlsdeploy/tool/deploy/deployer.py, core/src/main/python/wlsdeploy/tool/util/wlst_helper.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Don't merge unset properties from domain during online update.
Fixes #660
=> Avoid default JNDI name list for merge

site/create.md, site/deploy.md, site/update.md
Add the Encrypt model section from create.md to deploy.md and update.md
=> Add encrypt info to deploy and update

README.md, site/config/target_env.md, site/discover.md, site/prepare.md, site/samples/configured_cluster.md, site/samples/jdbc.md, site/samples/work_manager.md, site/security_providers.md, site/security_users_groups_roles.md, site/server_groups.md
- extract target config into separate page
- link to/from prepare model tool
- link to/from discover tool
- fix title levels after README reorganization
- match titles to links after README reorganization
Internal Jira WDT-434
=> Document vz target

core/src/main/python/create.py, core/src/main/python/deploy.py, core/src/main/python/discover.py, core/src/main/python/encrypt.py, core/src/main/python/extract_resource.py, core/src/main/python/model_help.py, core/src/main/python/prepare_model.py, core/src/main/python/update.py, core/src/main/python/validate.py, core/src/main/python/variable_inject.py
Remove path modification for Jython tools.
Internal Jira WDT-15
=> Prepend local package path to avoid conflicts with pwd

core/src/main/python/wlsdeploy/tool/modelhelp/model_sample_printer.py, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/Partition.json, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/PartitionWorkManager.json, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/ResourceGroup.json, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/ResourceGroupTemplate.json, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/VirtualTarget.json, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
=> Hide MT folders in modelHelp for WLS versions that don't support them

site/model_help.md
=> Revise documents to show model sample output

Jenkinsfile
Build and run integration tests nightly.  Publish nightly build installer to OCI object store for integration tests outside this project.
=> created nightly build with published installer

KnownIssues.md, README.md
The hot-linked headings in the README weren't aligned with good writing style guidelines, so I added a sentence beneath each of them. Feel free to suggest edits or other text.
=> minor improvements

site/rcuinfo.md
Documentation corresponding to the new RCU extended XML file command line argument.
=> Wdt 442 rcu enhancement documentation

core/src/main/python/validate.py, core/src/main/python/wlsdeploy/util/cla_utils.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
=> Allow no model present for standalone validate using lax method

core/src/main/python/prepare_model.py, core/src/main/python/wlsdeploy/tool/util/targets/vz_config_helper.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, core/src/main/resources/oracle/weblogic/deploy/targets/vz/binding.yaml, core/src/main/resources/oracle/weblogic/deploy/targets/vz/model.yaml
Also corrected prepareModel log message.
Internal JIRA WDT-540
=> Omit empty sections in VZ resource files

core/src/main/python/wlsdeploy/tool/util/targets/vz_config_helper.py, core/src/main/python/wlsdeploy/util/target_configuration_helper.py, core/src/main/resources/oracle/weblogic/deploy/targets/vz/model.yaml
Also don't create secret.
Internal Jira WDT-452
=> Remove runtime encryption secret from Verrazzano model.yaml

core/src/main/python/wlsdeploy/json/json_translator.py
=> Escape backslash characters when writing JSON

core/src/main/python/wlsdeploy/tool/create/domain_creator.py
=> Use correct signature for non-ATP RCURunner during create

core/src/main/java/oracle/weblogic/deploy/util/FileUtils.java, core/src/main/python/wlsdeploy/util/target_configuration_helper.py, core/src/main/targetconfigs/k8s/k8s_operator_filter.py, core/src/main/targetconfigs/vz/vz_filter.py, core/src/main/targetconfigs/wko/wko_operator_filter.py, core/src/test/python/target_configuration_helper_test.py
Also, avoid chmod on Windows.
Also, removed ServerStart from Server and ServerTemplate in filters.
=> Ensure that secret names follow established rules

core/src/main/python/wlsdeploy/tool/util/variable_injector_functions.py, core/src/main/python/wlsdeploy/util/target_configuration_helper.py, core/src/test/python/wlsdeploy/tool/util/variable_injector_functions_test.py
=> Correct variable tokens at discover time

core/src/main/java/oracle/weblogic/deploy/util/WLSDeployArchive.java, core/src/main/python/wlsdeploy/tool/deploy/deployer.py, core/src/main/python/wlsdeploy/tool/deploy/jms_resources_deployer.py, core/src/main/python/wlsdeploy/tool/discover/jms_resources_discoverer.py
Allow a directory of .binding files for ForeignServer ConnectionURL attribute. Archive the files and unzip on create domain.
#726
=> Wdt 05017 archive binding directory

core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py
Deployments were the only mbeans that threw an exception when the item to be deleted does not exist. Changed to line up with the rest of the deletes to log a WARN if entity to be deleted does not exist.
Had to put a few checks into the code to prevent the not existing delete did not get processed further.
=> WDT Warn instead of Exception on deleted app not found

pom.xml
Update JUnit to current version.
=> update junit version to 4.13

core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/SecurityConfiguration.json
Did not have plural in alias definition
This is needed by eucommission.
=> Auditor not discovered in online mode

site/config/target_env.md, site/prepare.md
Also adding `wls_credentials_name` description
Internal Jira WDT-461
=> Documentation for WKO template changes

site/tool_configuration.md
insert a section for the tool.properties properties
=> WDT-476-documentation

core/src/main/python/wlsdeploy/tool/util/targets/additional_output_helper.py
For target `wko` and `vz` model.yaml and binding.yaml.
Fixes #760
=> Domain name and prefix should follow DNS-1123

core/src/main/python/discover.py, core/src/main/python/prepare_model.py, core/src/main/python/wlsdeploy/tool/util/targets/additional_output_helper.py, core/src/main/python/wlsdeploy/util/target_configuration_helper.py, core/src/main/targetconfigs/vz/model.yaml, core/src/main/targetconfigs/wko/model.yaml
Exclude admin secrets.
Needs VZ changes to apply these.
Internal Jira WDT-498
=> Add a list of secrets to domain resource for WKO and VZ targets

core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Fixes #767
Internal Jira WDT-499
=> Create domain home directory for archive extraction before create

core/src/main/python/wlsdeploy/tool/deploy/applications_version_helper.py
=> Leave version in app name if no version in the manifest

core/src/main/python/discover.py, core/src/main/python/prepare_model.py, core/src/main/python/wlsdeploy/tool/util/credential_injector.py, core/src/main/python/wlsdeploy/util/cla_helper.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, core/src/test/python/wlsdeploy/util/cla_helper_test.py
Renamed method to merge_model_dictionaries() for public access.
Internal Jira WDT-475
=> Remove unused variables from credential cache

site/kubernetes.md
=> Revise README for updated WKO schema

core/src/main/java/oracle/weblogic/deploy/create/RCURunner.java, core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/python/wlsdeploy/tool/create/rcudbinfo_helper.py, core/src/main/python/wlsdeploy/util/model_context.py
Fix problems using RCUDbInfo in model with non-ATP DB.
Fixes #779 
Internal Jira WDT-508
=> Put RCU XML arguments in correct order

core/src/main/python/wlsdeploy/tool/discover/discoverer.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Fix for exception message that was causing its own exception message.
Fixes #795
=> Fix message problem for exception during offline discover 10.3.6

core/src/main/python/compare_model.py, core/src/test/python/compare_model_test.py, core/src/test/resources/compare_model_model6.yaml, core/src/test/resources/compare_model_model7.yaml, core/src/test/resources/compare_model_model8.yaml
Remove global use in compare_model.py and add more compare models test
=> Morecomparetest

core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py
=> Convert empty application targets to empty list and set

core/src/main/python/compare_model.py
Boolean check returned False for topology (no folders) location.
Internal Jira WDT-524
=> Compare model: check attributes location correctly

core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py, core/src/main/python/wlsdeploy/util/model_context.py
Fixes #797
Internal Jira WDT-523
=> Allow non-archive libraries in online deploy; fix invalid method

core/src/main/python/update.py
=> Update resources after setting server groups in offline update

core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/Server.json, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/ServerTemplate.json
Cannot discover or create this MBean in online WLST.
=> Add offline DebugScope MBean to ServerDebug

core/src/main/python/wlsdeploy/tool/create/domain_creator.py
Once again fix for createDomain - JDBC resources were targeted to AdminServer
=> Fix for admin server targeted to JDBC resources

core/src/main/python/wlsdeploy/tool/extract/domain_resource_extractor.py, core/src/main/python/wlsdeploy/tool/extract/wko_schema_helper.py, core/src/main/python/wlsdeploy/tool/modelhelp/model_kubernetes_printer.py, core/src/main/targetconfigs/vz/model.yaml, core/src/test/python/wlsdeploy/tool/extract/kubernetes_schema_test.py
Updated modelHelp to show enum values where available.
Changes made in the `JIRA-WDT-522-vz-oam-descriptors` branch as well.
Internal Jira WDT-530
=> Set domain source type default for extractResource and target resource files

samples/docker-domain/Dockerfile
changed --chown to oracle:root because base image ownership changed
=> Change permission because the base image changed ownership

core/src/test/python/compare_model_test.py, system-test/src/test/java/oracle/weblogic/deploy/integration/BaseTest.java, system-test/src/test/java/oracle/weblogic/deploy/integration/ITWdt.java, system-test/src/test/resources/simple-topology1-lessattribute.yaml
There are some logic in the operator code depends on WDT behavior to report errors or changing update behavior, this is the first series of tests added to ensure future changes does not impact WKO.
=> Add unit test and integration test for compareModel

core/src/main/python/wlsdeploy/tool/util/wlst_helper.py
=> Check for isSet method before calling

core/src/main/python/wlsdeploy/tool/create/atp_helper.py, core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/python/wlsdeploy/tool/create/domain_typedef.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, site/rcuinfo.md
I added more error detection for ATP and return a more meaningful error messages.
=> Atp harden error detection

core/src/main/java/oracle/weblogic/deploy/json/AbstractJsonTranslator.java
TypeUtils will convert to string or boolean appropriately.
Internal JIRA-WDT-544
=> In JSON parser, convert booleans to lower-case string value

core/src/main/python/wlsdeploy/tool/validate/validation_utils.py, core/src/test/resources/simple-model.yaml
=> Validate should recognize that float can be converted to string

Jenkinsfile
Use new main branch instead of master.
=> update Jenkinsfile to use renamed master branch

README.md, documentation/1.9/content/_index.md, documentation/1.9/content/developer/ReleaseProcess.md, documentation/1.9/content/release-notes.md
Touch ups and tweaks, nothing major.
=> minor text edits

documentation/1.9/content/_index.md, documentation/1.9/content/concepts/archive.md, documentation/1.9/content/concepts/model.md, documentation/1.9/content/developer/ReleaseProcess.md, documentation/1.9/content/developer/buildWDT.md, documentation/1.9/content/developer/contribute.md, documentation/1.9/content/samples/cluster-model.md, documentation/1.9/content/samples/jdbc-model.md, documentation/1.9/content/samples/odl-model.md, documentation/1.9/content/samples/ohs-model.md, documentation/1.9/content/samples/securityproviders-model.md, documentation/1.9/content/samples/workmanager-model.md, documentation/1.9/content/userguide/target_env.md, documentation/1.9/content/userguide/tools-config/custom_config.md, documentation/1.9/content/userguide/tools-config/model_filters.md, documentation/1.9/content/userguide/tools/compare.md, documentation/1.9/content/userguide/tools/create.md, documentation/1.9/content/userguide/tools/deploy.md, documentation/1.9/content/userguide/tools/discover.md, documentation/1.9/content/userguide/tools/encrypt.md, documentation/1.9/content/userguide/tools/kubernetes.md, documentation/1.9/content/userguide/tools/model_help.md, documentation/1.9/content/userguide/tools/prepare.md, documentation/1.9/content/userguide/tools/update.md, documentation/1.9/content/userguide/tools/validate.md
Add dollar sign before commands; other minor content re-org.
=> edit commands

documentation/1.9/content/_index.md
=> fix xref to WIT

core/src/main/python/wlsdeploy/util/cla_helper.py, core/src/test/python/validation_test.py
=> Fix validation test to run on windows and linux

core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/python/wlsdeploy/tool/util/default_authenticator_helper.py
=> Remove print statements from source

core/src/main/python/wlsdeploy/tool/create/domain_creator.py
Fixes issue #903
fix boot.properties being created for deleted server.
=> fix boot.properties created for deleted server

core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
The fixes WLSDPLY-01739  for resolution of secrets messages to be more clear and remove the word Error to avoid lax method confusion.
=> Fix error msg

core/src/main/python/wlsdeploy/tool/util/variable_injector.py, core/src/main/python/wlsdeploy/util/target_configuration_helper.py
=> Avoid copying variable file to itself; remove commented code

core/src/main/python/wlsdeploy/tool/util/default_authenticator_helper.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Corrected the encryption method used to encrypt the user password in DefaultAuthenticationInit.ldift
=> Fix for User password that was encrypted incorrectly

core/src/main/python/wlsdeploy/tool/discover/deployments_discoverer.py
plan path dir was not correctly resolved preventing it from being added to archive file.
Fixes Issue #923
=> plan path tokens not resolved creating an invalid plan path name

core/src/main/python/wlsdeploy/tool/validate/validator.py, documentation/1.9/content/userguide/tools/validate.md
=> validate should take multiple variable files

documentation/1.9/content/concepts/model.md
=> delete removing items from a list attribute

core/src/main/python/prepare_model.py, core/src/main/python/wlsdeploy/tool/util/credential_injector.py, core/src/main/python/wlsdeploy/tool/util/variable_injector.py
This PR change an attribute value to `@@SECRET:xxx`  if it is a credential field regardless of whether it's value is already a property.
=> Tokenize credential attributes even if it's value is already a property

core/src/main/antlr4/oracle/weblogic/deploy/yaml/Yaml.g4
=> Fix issue 940

core/src/main/python/wlsdeploy/tool/validate/kubernetes_validator.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Checked other calls for these messages.
Internal JIRA WDT-571
=> Add name list to messages 05026 and 05029, pass value in k8s validator

core/src/main/python/wlsdeploy/tool/create/domain_creator.py
in createDomain, if the server template listen port is 7001, a work around is taken to set the port after the server port as it will not show up in the config.xml if set before.
=> Set server template listen port after server listen port

installer/src/main/bin/shared.cmd
=> Remove double quotes each argument as it is tested

core/src/main/python/extract_resource.py, core/src/main/python/wlsdeploy/tool/extract/domain_resource_extractor.py, core/src/main/python/wlsdeploy/tool/util/k8s_helper.py, core/src/main/python/wlsdeploy/tool/util/targets/additional_output_helper.py
… , regardless of WLS version.
Removed unneeded alias dependencies.
Internal JIRA WDT-574
=> Derive replica count from DynamicClusterSize or MaximumDynamicServerCount

core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py, core/src/main/python/wlsdeploy/tool/deploy/deployer.py, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/AppDeployment.json
Fixes #951 
Allows Subdeployment folder in AppDeployments and Libraries
=> Allow Subdeployments in App

core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py
=> allow relative path in appdeploy and update onine

documentation/1.9/content/samples/wtc-model.md
Documentation for a model sample using WTC
=> sample for WTC

documentation/1.9/content/concepts/archive.md
documentation on custom archive file
=> add custom directory to archive structure doc

core/src/main/python/wlsdeploy/json/json_translator.py
This fixes the encoding logic for string values in the dictionary when translating to json
Fixes #999
=> Fix characters encoding logic to provide validate json output

core/src/main/python/wlsdeploy/tool/create/domain_creator.py
Fixes #1004 
Domain creation did not have the extract archive files. Readd.
=> extract custom files in createDomain

core/src/main/python/wlsdeploy/json/json_translator.py
Fix logic to escape text value for multiple characters need to be escaped.
=> Fix json translater logic

core/src/main/python/wlsdeploy/tool/deploy/deployer_utils.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
corrected i18n error message number _09015 to match the format of other message numbers
=> corrected i18n error message number _09015 

core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/python/wlsdeploy/tool/create/domain_typedef.py, core/src/main/python/wlsdeploy/tool/util/topology_profiles.py, core/src/main/python/wlsdeploy/tool/util/wlst_helper.py, core/src/main/python/wlsdeploy/util/weblogic_helper.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, core/src/main/typedefs/JRF-Compact.json
=> Topology profile

documentation/2.0/content/concepts/model.md, documentation/2.0/content/release-notes.md, documentation/2.0/content/userguide/target_env.md, documentation/2.0/content/userguide/tools-config/domain_def.md, documentation/2.0/content/userguide/tools-config/model_filters.md
** This does not include Release Notes changes - those are being handled separately **
=> Documentation updates for 2.0

alias-test/pom.xml, core/pom.xml, core/src/main/python/wlsdeploy/tool/discover/discoverer.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, installer/pom.xml
=> Eliminate use of MBeanInfo for discovery

core/src/main/python/wlsdeploy/tool/create/atp_helper.py, core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
This PR is to improve the error messages when getting the ATP connection string from the wallet.
=> Improve ATP error message

core/src/main/python/wlsdeploy/tool/util/default_authenticator_helper.py
Fixes Jira #600
Check for None before checking for len on item.
=> look for None before checking len

core/src/main/python/wlsdeploy/tool/create/atp_helper.py
Correct read mode of atp wallet causing permission deny
=> Correct ATP wallet read mode causing permission deny

core/src/main/java/oracle/weblogic/deploy/util/WLSDeployArchive.java, core/src/main/python/prepare_model.py, core/src/main/python/wlsdeploy/tool/discover/domain_info_discoverer.py, core/src/main/python/wlsdeploy/tool/prepare/model_preparer.py, core/src/main/python/wlsdeploy/tool/util/archive_helper.py, core/src/main/python/wlsdeploy/util/cla_utils.py, core/src/main/python/wlsdeploy/util/model_context.py, core/src/main/python/wlsdeploy/util/target_configuration.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, core/src/main/targetconfigs/vz/target.json, core/src/main/targetconfigs/wko/target.json, installer/src/main/bin/prepareModel.cmd, installer/src/main/bin/prepareModel.sh
=> Wdt 539 provide configurable setting for targets to exclude domain bin scripts in discover and prepare model 

documentation/2.0/content/userguide/tools-config/domain_def.md
Fixes Jira #360
Add documentation for the system-elements section of the typedef file.
=> document typedef file system-elements section

core/src/main/java/oracle/weblogic/deploy/yaml/AbstractYamlTranslator.java, core/src/main/java/oracle/weblogic/deploy/yaml/YamlStreamTranslator.java, core/src/main/java/oracle/weblogic/deploy/yaml/YamlTranslator.java, core/src/main/python/compare_model.py, core/src/main/python/wlsdeploy/yaml/yaml_translator.py, core/src/test/python/wlsdeploy/yaml/yaml_translator_test.py, core/src/test/resources/yaml/multiple-docs.yaml
Also fixed problem with compareModel write to stdout
=> Add methods to read/write multiple-document YAML files

core/src/main/java/oracle/weblogic/deploy/util/XPathUtil.java, core/src/test/java/oracle/weblogic/deploy/util/XPathUtilTest.java
=> Parse off parentheses from psu name

alias-test/pom.xml, core/pom.xml, core/src/main/python/wlsdeploy/tool/extract/domain_resource_extractor.py, core/src/main/python/wlsdeploy/tool/extract/wko_schema_helper.py, core/src/main/python/wlsdeploy/tool/util/targets/additional_output_helper.py, core/src/main/python/wlsdeploy/tool/util/targets/file_template_helper.py, core/src/main/python/wlsdeploy/tool/util/targets/output_file_helper.py, core/src/main/python/wlsdeploy/tool/util/targets/resource_file_helper.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, core/src/main/targetconfigs/templates/vz-application.yaml, core/src/main/targetconfigs/templates/wko-domain.yaml, core/src/test/python/wlsdeploy/tool/util/filters/output_file_helper_test.py, core/src/test/resources/wko/k8s-model.yaml, core/src/test/resources/wko/wko-domain.yaml, installer/pom.xml, pom.xml, system-test/pom.xml
Also:
- Updated POM versions to 2.1.0 for next release.
- Fixed mustache problem affecting runtime-encryption-secret.
Documentation will be a separate PR.
Internal JIRA WDT-607
=> Merge model kubernetes section into target output file

installer/src/main/bin/shared.cmd, installer/src/main/bin/shared.sh
=> honor existing WLST_EXT_CLASSPATH environment variable settings when invoking tools

core/src/main/python/wlsdeploy/aliases/alias_constants.py, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/SecurityConfiguration.json
use long name for offline
Fixes Jira #621 
Tested in 12.2.1.4 and 14.1.1
=> Correct name for JDCSIntegrator

core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/Server.json
Apply attributes after final.py of template is performed
Tested with various scenarios
=> Wdt 983 third pass of updates

core/src/main/python/wlsdeploy/tool/validate/validation_utils.py
=> Make unicode data type compatible with itself

core/src/main/python/wlsdeploy/tool/validate/validator.py, core/src/main/python/wlsdeploy/util/variables.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, system-test/src/test/java/oracle/weblogic/deploy/integration/ITWdt.java
Fixes Jira WDT-616
check for variables for message about variable not in variables list.
=> reduce the number of messages for no property file

documentation/2.0/content/rcuinfo.md
Reference Oracle PKI Provider document
=> document oracle pki provider

Jenkinsfile, core/src/main/python/wlsdeploy/tool/util/targets/output_file_helper.py, core/src/main/python/wlsdeploy/util/dictionary_utils.py
This fixes a problem preventing nested model elements from being type-converted or flattened when merging the model section with the generated file in extractDomainResource and when using -target.
=> Process newly added elements recursively for extract domain resource

core/src/main/python/discover.py
=> Revised field keys in discover result output file

core/src/main/python/wlsdeploy/tool/util/targets/additional_output_helper.py, core/src/main/python/wlsdeploy/tool/util/targets/output_file_helper.py, core/src/main/python/wlsdeploy/util/target_configuration.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, core/src/main/targetconfigs/templates/vz-application.yaml, core/src/main/targetconfigs/templates/wko-domain.yaml, core/src/test/python/wlsdeploy/tool/extract/extract_test.py
Provide target switch to enable.
Add comment for adding cluster replica count.
=> Remove cluster replica count from domain resource file by default

core/src/main/python/wlsdeploy/tool/util/targets/output_file_helper.py
This will ensure that comments are added as needed.
=> Update WKO domain.yaml even when there is no kubernetes section in the model

system-test/src/test/resources/archive/simple-app/WEB-INF/web.xml, system-test/src/test/resources/archive/simple-app/WEB-INF/weblogic.xml, system-test/src/test/resources/archive/simple-app/simple.html, system-test/src/test/resources/build-archive.sh
*** Confirmed that simple-app.war and archive.zip are correct in the pr-merge workspace ***
Exit if any of the `cd` commands fail.
Internal Jira WDT-656
=> Build simple-app.war correctly for system test

core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py, system-test/src/test/java/oracle/weblogic/deploy/integration/BaseTest.java, system-test/src/test/java/oracle/weblogic/deploy/integration/ITWdt.java, system-test/src/test/resources/simple-topology-onlinebase.yaml, system-test/src/test/resources/simple-topology-targetapp.yaml, system-test/src/test/resources/simple-topology-untargetapp.yaml, system-test/src/test/resources/update-archive.sh
This PR add system test for online application untarget, retarget, and deploy new version.
=> Update system test for online app updateDomain

core/src/main/python/wlsdeploy/tool/discover/custom_folder_helper.py
Fixes Jira 645
needed better message for missing schematype file
=> Make message a warning for need schematype file

alias-test/src/test/python/aliastest/verify/verifier_helper.py, core/src/main/java/oracle/weblogic/deploy/util/WLSDeployArchive.java
No Jira opened on this issue. Overrides file was gathering duplicate files.
=> Wdt duplicate overrides

core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/CoherenceClusterSystemResource.json, integration-tests/alias-test/verify/src/test/python/aliastest/verify/verifier.py
Targets online was marked with LSA instead of GET
=> fix the alias definition

core/src/main/python/wlsdeploy/tool/discover/domain_info_discoverer.py
=> Don't add domain libraries when -skip_archive is specified

integration-tests/alias-test/verify/src/test/python/aliastest/verify/verifier.py
order of entries in flattened dictionary is random. Find the correct location so can successfully get rid of flattened part of dictionary.
=> Fix previous fix

integration-tests/alias-test/verify/src/test/python/aliastest/verify/alias_helper.py, integration-tests/alias-test/verify/src/test/python/aliastest/verify/verifier.py
access=ROD is readonly as is access=RO. Treat the ROD attributes as read_only for the test.
=> understand what is effectively readonly fields

integration-tests/alias-test/verify/src/test/python/aliastest/verify/verifier.py
When lsa type has unknown, check type for list type if alias_type is not equal to wlst_type
=> look at list type in lsa

core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/SystemComponent.json, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/WebserviceSecurity.json
Also changed their model names
=> WIP: Corrected offline attribute names MwHome and DefaultCredentialProviderStsuri

core/src/main/python/deploy.py, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/WTCServer.json, integration-tests/alias-test/generate/src/test/python/aliastest/generate/generator_online.py
Also fixes problem with WDT online deploy crashing
=> Alias changes for WTCServer

integration-tests/alias-test/generate/src/test/python/aliastest/generate/generator_base.py, integration-tests/alias-test/generate/src/test/python/aliastest/generate/generator_wlst.py
Added tokenization values.
Use names of ObjectName values.
=> Alias test generator changes

Jenkinsfile, core/pom.xml, core/src/main/python/wlsdeploy/tool/util/targets/file_template_helper.py, core/src/test/python/base_test.py, core/src/test/python/wlsdeploy/tool/extract/extract_test.py, core/src/test/python/wlsdeploy/tool/prepare/prepare_test.py
=> making WDT custom config available for unit tests

core/src/main/python/wlsdeploy/tool/create/atp_helper.py, core/src/test/python/atp_helper_test.py
port 2.4 atp wallet changes back to main
=> port atp wallet related changes to main

documentation/3.0/content/userguide/tools/archive_helper.md
First pass at doc for Archive Helper Tool. I would like to add more examples to the **Usage scenarios** but would need input for some of the most useful ones. Regarding two examples I added, I should probably use different file paths and file names but again, I'm not sure what they should be. Your ideas and suggestions are welcome.
=> Add doc for archive helper

core/src/main/python/wlsdeploy/tool/deploy/deployer.py, core/src/main/python/wlsdeploy/util/validate_configuration.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Remove duplicate message in deploy/update.
Fixes internal Jira WDT-724
=> Use INFO message for version-invalid attributes in model

core/src/main/python/wlsdeploy/tool/discover/topology_discoverer.py
=> remove empty folder from security configuration
