oracle/weblogic-deploy-tooling

core/src/main/python/wlsdeploy/tool/validate/validator.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, core/src/test/python/validation_test.py
Changed validator to not report it as a validation result error, if the model dictionary has an attribute value with a '${' sequence, but no matching properties file entry. Now it just logs it as a warning level log message, and keeps validating.
=> Issue#64 deprecate using ${ as variable substitution expression

core/src/main/python/update.py, core/src/main/python/wlsdeploy/tool/create/creator.py, core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/python/wlsdeploy/tool/create/security_provider_creator.py, core/src/main/python/wlsdeploy/tool/deploy/topology_updater.py, core/src/main/python/wlsdeploy/tool/util/library_helper.py, core/src/main/python/wlsdeploy/tool/util/target_helper.py, core/src/main/python/wlsdeploy/tool/util/topology_helper.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, installer/src/main/bin/updateDomain.cmd, installer/src/main/bin/updateDomain.sh
Add update domain capability. Fixes #95
=> Issue#95 add update domain capability

core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py
This is a fix to address the issue when the war, ear, jar shared library is packed with Sun's pack200 method causing the wlst python library throwing BadZipException when computing the required deploy name for the file, switching to java will ensure compatibility with pack200.
=> Pack200fix

core/src/main/python/wlsdeploy/aliases/alias_utils.py
Convert TypeError to AliasException when thrown. Fixes #123
=> Issue#123 - Convert TypeError to AliasException when thrown

core/src/main/python/wlsdeploy/tool/discover/common_resources_discoverer.py, core/src/main/python/wlsdeploy/tool/discover/discoverer.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
We still need to determine why the exception domain differs from our expectations of what the /Server/Log directory should be named, and determine if it is a problem that we need to consider and solve.
However, the correct action would be to warn the user and continue with the discover, not end immediately on this type of condition.
=> Do not end discover if wlst.cd() fails

samples/docker-domain/Dockerfile, samples/docker-domain/README.md, samples/docker-domain/container-scripts/domain.properties, samples/docker-domain/container-scripts/startManagedServer.sh, samples/docker-domain/container-scripts/startWLSDomain.sh, samples/docker-domain/properties/domain.properties, samples/docker-domain/simple-topology.yaml
Also use WLS quick install sample as image basis, use production start mode. Fixes #134
=> Issue#134 access property file from mounted volume

core/src/main/python/wlsdeploy/tool/discover/discoverer.py, core/src/main/python/wlsdeploy/tool/discover/topology_discoverer.py
Changed the code that checks to see if the NMProperties mbean exists in the domain.
=> Add code to discover if a top level folder exists in the domain

core/src/main/java/oracle/weblogic/deploy/aliases/VersionUtils.java, core/src/main/python/wlsdeploy/tool/util/filter_helper.py, installer/src/main/etc/logging.properties
Please do not delete the repository or close the corresponding issue for this pull request until you have read the below:
I changed the logging properties to set the aliases and versions loggers to level FINE. This will reduce the ENTER, EXIT chatter. We can request the end user to change those logger levels if needed. However, the quality of logs in the aliases is not ideal. Informative loggers at the FINE level should be added to the aliases code. I have yet to find the information I need for an alias issue from the entering,exiting code. Entering,Exiting loggers is about all that aliases logs except for those at INFO and above.
If setting the version and alias loggers to level FINE is acceptable, we can close the issue and delete the repository. I suggest we open another issue for …
=> modifications for log chatter

core/src/main/python/wlsdeploy/tool/create/domain_typedef.py, core/src/main/python/wlsdeploy/tool/discover/coherence_resources_discoverer.py, core/src/main/python/wlsdeploy/tool/discover/common_resources_discoverer.py, core/src/main/python/wlsdeploy/tool/discover/deployments_discoverer.py, core/src/main/python/wlsdeploy/tool/discover/global_resources_discoverer.py, core/src/main/python/wlsdeploy/tool/discover/jms_resources_discoverer.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Examples:
<Skipping JRF shared library oracle.jsp.next#12.2.1@12.2.1>
<Skipping JRF application wsm-pm>
Fixes #199 again
=> Added domain type name to logging for skipping system resources

core/src/main/java/oracle/weblogic/deploy/yaml/AbstractYamlTranslator.java
The NPE no longer occurs.  The parse error is still detected on the next line number in this scenario, but there are additional messages that point to the JdbcResource model entry.  Fixes #208
=> JIRA WDT-46 Avoid assigning non-parsable value in YAML

installer/src/main/bin/createDomain.cmd, installer/src/main/bin/createDomain.sh, installer/src/main/bin/deployApps.cmd, installer/src/main/bin/deployApps.sh, installer/src/main/bin/discoverDomain.cmd, installer/src/main/bin/discoverDomain.sh, installer/src/main/bin/encryptModel.cmd, installer/src/main/bin/encryptModel.sh, installer/src/main/bin/injectVariables.cmd, installer/src/main/bin/injectVariables.sh, installer/src/main/bin/updateDomain.cmd, installer/src/main/bin/updateDomain.sh, installer/src/main/bin/validateModel.cmd, installer/src/main/bin/validateModel.sh
Add check for invalid domain_type in shell script, if it is not set then it will set to WLS and if it is not equals to one of WLS|JRF|RestrictedJRF it will exit with an error message; since the shell scripts are the only entry points, no need to fix it in python.
=> Wdt 33 domaintypechk

core/src/main/python/wlsdeploy/tool/create/creator.py, core/src/main/python/wlsdeploy/tool/create/security_provider_creator.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Don't create or update security configuration adjudicators. Warn if the model has non-default configuration.
There is some refactoring that makes the code review complicated:
- SecurityProviderCreator.__get_default_realm_location() removed (was already dead)
- Creator._delete_existing_providers() moved to SecurityProviderCreator
- Creator._create_security_provider_mbeans() renamed _create_named_subtype_mbeans(), content moved to SecurityProviderCreator() override method
- Creator._create_subfolders() moved within file
- new methods SecurityProviderCreator._check_provider_type() and _is_default_adjudicator_configuration()
=> WDT-257 - Don't create or update security configuration adjudicators.

core/src/main/java/oracle/weblogic/deploy/util/WLSDeployZipFile.java
Prior than jdk 8,  java.io.File generateFile does not strip down the prefix to base name in createTempFile, we are changing how we pass in the prefix now.
=> Fix how we calculate temporary file for archive

core/src/main/python/wlsdeploy/tool/discover/deployments_discoverer.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Correct discover domain log message for application deployment plan.  The log message was pointing at the library deployment plan message.
=> Correct discover domain log message for application deployment plan

core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/python/wlsdeploy/tool/create/domain_typedef.py, core/src/main/python/wlsdeploy/tool/deploy/topology_updater.py
Only do applyJRF if running with a -domain_type that has JRF template server group. Reported by Richard Killen on 10.3.6 running -domain_type WLS
=> Dont apply jrf resources if running domain_type WLS

README.md, core/src/main/python/wlsdeploy/aliases/model_constants.py, core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/python/wlsdeploy/tool/deploy/topology_updater.py, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/Domain.json, site/admin_server.md
Avoid misleading logging on create when admin server name is in model; discover admin server name.
Added a document describing admin server configuration.
=> JIRA WDT 299 admin server name problems

core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/python/wlsdeploy/tool/create/domain_typedef.py, core/src/main/python/wlsdeploy/tool/util/wlst_helper.py, core/src/main/python/wlsdeploy/util/wlst_helper.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, core/src/main/typedefs/JRF.json, core/src/main/typedefs/RestrictedJRF.json, core/src/main/typedefs/WLS.json, site/create.md
Added customExtensionTemplates property to typedefs.
For 12c, custom extension templates are selected using selectCustomTemplate().
For 11g, they are treated the same as extension templates.
Fix to update the domain after adding templates for 11g non-JRF.
Fixes #359
=> Issue #359 - Support custom extension templates

core/src/main/python/wlsdeploy/tool/discover/custom_folder_helper.py
Typo introduced into method name when changing some of the python doc.
=> Fix typo in method name for custom_folder_helper

core/pom.xml, pom.xml
The -D will continue to work.  But, this will allow the value to be set as an ENV variable (WLST_DIR), also.  This change will make it a little easier to deal with in Docker containers.
=> allow WLST directory property to be set in the environment

core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
The application name should match the model, and be appended with the version number when the "Weblogic-Application-Version" attribute is set in the ear/war manifest.
The rules for deployed libraries should remain as they are, but should not consider "Weblogic-Application-Version".
Fixed syntax error in message WLSDPLY-09327 .
Fixes #434
=> Issue #434 - Use separate rules for application version naming

core/pom.xml, pom.xml, site/developer/developer_guide.md
Simplify build experience for non-developers.
=> updated wlst unit test plugin and removed enforcer

core/src/main/python/wlsdeploy/tool/discover/discoverer.py, core/src/main/python/wlsdeploy/tool/util/mbean_utils.py
14.1.1 version of jython does not create strings for instances the same as in the early version of jython. The change made to handle all versions worked for 14.1.1.0.0 and 12.2.1.3.0 but broke in 10.3.6. Made a fix to handle for all versions.
=> fix for domain discover issue found in 10.3.6 but not 12.2.1.3

core/src/main/python/wlsdeploy/aliases/aliases.py, core/src/test/python/alias_encrypted_model_test.py, site/encrypt.md
Use the model-decrypted value of password attributes to determine if the WLST attribute name should change.
Document that encryptModel should not be used in tandem with domain-encrypted model passwords.
Separated unit tests for password attributes and model encryption.
Fixes #484
=> Issue #484 - Use of model encryption with online update fails

core/src/main/antlr4/oracle/weblogic/deploy/yaml/Yaml.g4
=> Issue #486 - Allow identifiers to begin with a digit, allowed by WLS

core/src/main/python/wlsdeploy/tool/util/variable_injector.py, core/src/main/python/wlsdeploy/util/variables.py
If the variable map is in a PyOrderedDict instance, print to file insuring order
Remove old debug prints left behind from previous PR
=> WDT#479 sort variable file and remove old debug prints

core/src/main/python/discover.py, core/src/main/python/wlsdeploy/util/model_context.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, installer/src/main/bin/discoverDomain.cmd, installer/src/main/bin/discoverDomain.sh
Fix #503 
Add java home global token for ease of use when discovering attributes in the model that contain java home values.
Add -java_home argument to use a directory different than the one in JAVA_HOME when discovering such attributes (an oracle home domain with different java home)
=> Issue#503 add java home global token

core/src/main/python/wlsdeploy/tool/discover/common_resources_discoverer.py
The JMS credentials were not populated because not passed the variable injector.
=> inject jms credentials with variable property

core/src/main/java/oracle/weblogic/deploy/util/WLSDeployArchive.java, core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py, core/src/main/python/wlsdeploy/tool/deploy/deployer.py, core/src/main/python/wlsdeploy/tool/util/archive_helper.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
- unzip specified app directory in archive to wlsdeploy directory
- use the manifest from the file system if app is exploded
- for online, always redeploy exploded app, since hash can't be determined
=> Jira WDT-385 Enable exploded app in archive

core/src/main/python/wlsdeploy/aliases/model_constants.py, core/src/main/python/wlsdeploy/tool/discover/topology_discoverer.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Currently kss keystore files cannot be added to the archive and populated into the target domain. Warn instead of printing obscure message
1. WLSDPLY-06642: Custom Keystore file kss://system/ylidentity at location /Server/NetworkAccessPoint is a kss type which is not currently supported. The Custom Keystore file will not be added to the archive file. Use export / import to add the file to the target domain
Total:       WARNING :     1    SEVERE :     0
=> warn about not supported kss keystore type

core/src/main/python/wlsdeploy/tool/discover/discoverer.py
Bug introduced in late 2019, overlay of custom providers in recursive call.
This issue reported by Lars Pusa.
=> add instead of replace in recursive call

core/src/main/antlr4/oracle/weblogic/deploy/yaml/Yaml.g4, core/src/main/java/oracle/weblogic/deploy/logging/LoggingUtils.java, core/src/main/java/oracle/weblogic/deploy/yaml/AbstractYamlTranslator.java, core/src/test/java/oracle/weblogic/deploy/yaml/YamlJavaTranslator.java, core/src/test/java/oracle/weblogic/deploy/yaml/YamlParserCommentTest.java, core/src/test/java/oracle/weblogic/deploy/yaml/YamlParserTest.java, core/src/test/resources/yaml/comment-model.yaml
Fix several problems with YAML parsing:
- blank lines and comments at the top of the file
- empty comment lines like #
- comments after object block open, like domainInfo:  # mine
- single-line comments throwing off indentation
See new model comment-model.yaml for examples
Broke out YamlJavaTranslator for use in multiple unit tests.
Fixed compiler warning in LoggingUtils.
Fixes #236
=> Parser fixes

site/deploy.md
=> Correct statements regarding use of -domain_home argument with online deployment.

core/src/main/python/create.py, core/src/main/python/deploy.py, core/src/main/python/update.py, core/src/main/python/validate.py, core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/python/wlsdeploy/util/cla_helper.py, core/src/main/python/wlsdeploy/util/model.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
JIRA-WDT-392 
Enable for validateModel, deployApps, extractDomainResource.
Save to domain/wlsdeploy or temp dir if variable is not set to path.
Target file can be JSON or YAML, based on file extension.
=> Store merged, resolved model at the location specified in environment variable

core/src/main/java/oracle/weblogic/deploy/yaml/AbstractYamlTranslator.java, core/src/main/java/oracle/weblogic/deploy/yaml/YamlTranslator.java, core/src/main/python/wlsdeploy/json/json_translator.py, core/src/main/python/wlsdeploy/tool/validate/validator.py, core/src/main/python/wlsdeploy/yaml/yaml_translator.py
Most of these are in parsers, so too early to distinguish password attributes.
Method in validator could do more checking, but not worth it for FINER logging.
=> Avoid dumping model and model sections in the logs

core/src/main/antlr4/oracle/weblogic/deploy/yaml/Yaml.g4, core/src/test/resources/unit-test.yaml
Logging properties can have an asterisk in the name.  The YAML parser needs to support names with asterisks.  This change only allows asterisks in names with quotes.  Fixes #562 
Like:
```
managed-server-1:
Log:
LoggerSeverityProperties:
'my.package.*': Debug
```
=> allow asterisk in yaml for logging properties

core/src/main/python/wlsdeploy/util/variables.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Fixes #585 
Revised message examples:
```
<WLSDPLY-01746> <Invalid token syntax for ProductionModeEnabled value "@@PROP: ProductionModeEnabled@@", should match "@@PROP:<name>@@">
<WLSDPLY-01745> <Invalid token syntax for name "@@PROP: my-cluster", should match "@@PROP:<name>@@"
```
=> Issue #585 Improve error messages for token syntax errors

core/src/main/java/oracle/weblogic/deploy/util/PyOrderedDict.java, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, core/src/test/python/collections_test.py, pom.xml
In Jython 2.7, PyDictionary subclasses must set the type field in the parent class through the PyDictionary constructor.
=> Allow PyOrderedDict to work in Jython 2.7

site/samples/samples.md, site/samples/work_manager.md
=> Added sample model for Work Manager

core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py
For online application deployment
Fixes #631
=> Only extract /wlsdeploy paths from the archive

pom.xml
Guava version is used as comparator in system test. Tested WDT in addition to running system test.
=> Change guava version and run system tests

core/src/main/python/wlsdeploy/aliases/model_constants.py, core/src/main/python/wlsdeploy/tool/deploy/deployer.py, core/src/main/python/wlsdeploy/tool/deploy/deployer_utils.py, core/src/main/python/wlsdeploy/tool/discover/jms_resources_discoverer.py, core/src/main/python/wlsdeploy/util/model_context.py
Issue #525 requested that WDT collect the MQ Bindings for foreign jms connections. The tool was already collecting, but the resulting MBean attribute in createDomain was not valid. This fix corrects the problem.
The issue requested that the files be collected under domainHome in the archive file, along with other application files. Please review to see if there is additional work to be done.
The MQBindings are collected in wlsdeploy/jms/foreignServer/name of foreign server/
=> fix the collection and extraction of foreign connection binding files

core/src/main/python/compare_model.py
Changed the compareModel to run the Validator in standalone mode so that the archive file is not required. Since this is not a tool like create or discover, but a utility, there is no reason to run in a stricter mode.  No longer has the SummaryHandler totals which I think is reasonable.
1. Run validator in stand-alone mode
2. Fixed some obvious errors and pe8 warnings
=> Run validator in standalone mode so archive is not required

core/src/main/python/wlsdeploy/tool/discover/custom_folder_helper.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Without schema jar in the correct location, offline WLST will not properly discover a custom security provider MBean. Warn the user that the MBean not discovered.
=> Warn when schema information not present for custom security provider

site/create.md
Document that WDT creates a boot.properties with credentials for development domains
=> Document the boot.properties behavior in the README

core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/Partition.json, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/ServerTemplate.json, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/VirtualHost.json, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/VirtualTarget.json
Remove NO_NAME_0 as offline name for any MBean Log type.
NOTE: Should ServerTemplate Log have Server for name instead of ServerTemplate name?
=> remove NO_NAME_0 from Log MBean types

core/src/main/python/model_help.py, core/src/main/python/wlsdeploy/tool/modelhelp/model_help_printer.py, core/src/main/python/wlsdeploy/tool/modelhelp/model_sample_printer.py, core/src/main/python/wlsdeploy/util/cla_utils.py, core/src/main/python/wlsdeploy/util/model_context.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, installer/src/main/bin/modelHelp.cmd, installer/src/main/bin/modelHelp.sh
Use model sample output always, deprecate -model_sample command-line option.
Align attribute data type comments.
Correct security provider output.
Clarify output format comments.
Internal Jira WDT-435
=> Model help enhancements

core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/Server.json
Fixes #678 
Use server name for JTA migratable targets for offline and online.
WLS 12.2.1.4+, 14.1+ used NO_NAME literally, older versions disregarded it.
All versions OK applying server name directly.
=> Use server name for JTA migratable targets in offline mode

core/src/main/python/compare_model.py, core/src/main/python/wlsdeploy/tool/validate/validator.py, core/src/main/python/wlsdeploy/util/model_context.py, core/src/test/python/wlsdeploy/util/model_context_test.py, core/src/test/resources/compare_model_model3.yaml
1. validation called using model context without a model file. Added code to model_context to copy and add / override arguments. Created a model context copy for each model with the model file in the copied context.
2. compare model to run in validator in stand-alone-mode not completed. This was done becaause tool mode requires an archive file and other more strict policies. The second model file validate was not using stand alone tool mode. and stand alone tool mode not returning a return code from the validate. Fixed both
3. Fixed compare model test file to have something other than a requirement for archive file (not required anymore)
=> Wdt 433 compare model validation

core/src/main/python/wlsdeploy/logging/platform_logger.py, core/src/main/python/wlsdeploy/tool/discover/discoverer.py
1. Fix for logging arguments that are unicode, such as internationalized WLSTException messages
2. Fix in discover for catching DiscoverException instead of AliasException
Fixes #690
=> Issue#690 unicode logging issue

core/src/main/python/compare_model.py, core/src/test/python/compare_model_test.py, core/src/test/resources/compare_model_model5.yaml
Did a lot of testing and found only the removal of a top level causes the problem. Problem due to an undefined variable.
Fixes Jira WDT-436
=> Fix for top level removal between models

core/src/main/python/compare_model.py, core/src/main/python/wlsdeploy/yaml/yaml_translator.py
```
Comparing Models: new=.\online_dyn_new.yaml vs old=.\online_dyn.yaml
Differences between new model and old model:
domainInfo:
AdminUserName: weblogic
AdminPassword: welcome1
topology:
Server:
AdminServer:
Log:
MemoryBufferSize: 100
ms2:
ListenPort: 7005
'!c1-3':
MigratableTarget:
'!c1-3 (migratable)':
1. Model Path: topology-->Server-->AdminServer-->WebServer-->WebServerLog-->FileCount does not exist in new model but exists in previous model
2. Model Path: topology-->Server-->AdminServer-->WebServer-->WebServerLog-->FileMinSize does not exist in new model but exists in previous model
```
=> Comments in STDOUT for attributes whose values have changed

core/src/main/python/wlsdeploy/tool/util/k8s_helper.py, core/src/test/python/wlsdeploy/tool/util/k8s_helper_test.py
=> Ensure that domain UID from domain name conforms to DNS-1123

core/src/main/python/wlsdeploy/tool/util/targets/vz_config_helper.py, core/src/main/python/wlsdeploy/util/target_configuration_helper.py, core/src/main/resources/oracle/weblogic/deploy/targets/vz/model.yaml
Internal Jira WDT-452
model.yaml:
```
domainCRValues:
. . .
configuration:
model:
domainType: WLS
runtimeEncryptionSecret: demodomain-runtime-encryption
```
create_k8s_secrets.sh:
```
create_k8s_secret runtime-encryption <password> 
```
=> Add configuration/model section to model.yaml; create runtime encryption secret

KnownIssues.md
Added titles to each issue.
Corrected some general formatting.
=> README: Added known issue for SecurityConfiguration/CredentialEncrypted

core/src/main/java/oracle/weblogic/deploy/logging/WLSDeployLoggingConfig.java, core/src/main/java/oracle/weblogic/deploy/util/FileUtils.java, core/src/main/python/prepare_model.py, core/src/main/python/wlsdeploy/tool/util/variable_injector.py, core/src/main/python/wlsdeploy/util/target_configuration.py, core/src/main/python/wlsdeploy/util/target_configuration_helper.py, core/src/main/resources/oracle/weblogic/deploy/targets/vz/binding.yaml, core/src/main/targetconfigs/vz/target.json, core/src/main/targetconfigs/wko/target.json, core/src/main/targetconfigs/wko/wko_operator_filter.py, core/src/test/java/oracle/weblogic/deploy/util/FileUtilsTest.java, core/src/test/python/target_configuration_helper_test.py, site/config/target_env.md
* added new target type, wko
* added execute permissions to generated shell script from vz target
* corrected weblogic credential secret name for models targeted to WebLogic Operator
* changed generated Verrazzano binding defaults for DNS name to "*"
* changed generated Verrazzano binding namepace from default to {domainUid}-ns
* corrected log folder name from jcslcm-logs to wdt-logs
=> Changes for Verrazzano

core/src/main/python/wlsdeploy/tool/validate/validator.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
When a group is expected in the model, and a string is found, a stack trace occurs. This model has an indention problem, and and `Target` appears to be a JDBC name. The tools fail with a stack trace, expecting it to have a nested group instead of string.
JDBCSystemResource:
'Bubba-DS2':
Target: mycluster
JdbcResource:
stack trace snippet:
File "/u01/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/validate/validator.py", line 384, in _Validator__validate_model_section
File "/u01/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/validate/validator.py", line 461, in _Validator__validate_section_folder
File "/u01/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/validate/validator.py", line 532, in _Validator__process_model_node
AttributeError: 'string' object has no attribute 'iteritems'
=> Verify that sections are dictionaries, and not single values

core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/DomainInfo.json
Was failing validation, not in modelHelp.
Set AppDir option regardless of extension templates
=> Allow AppDir in model domainInfo section

core/src/main/python/wlsdeploy/tool/deploy/odl_deployer.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Use logging configuration template to configure ODL when server has not been created.
=> Enable ODL configuration for dynamic servers

core/src/main/python/compare_model.py
Pass empty variables map to validate to prevent crash (lines 458, 477)
Optimized imports (no changes).
A lot of whitespace changes to remove PEP-8 warnings.
Internal JIRA WDT-467
=> Fix compareModel stack dump when variables file not specified

core/src/main/python/compare_model.py, core/src/main/python/wlsdeploy/util/model_helper.py, core/src/main/python/wlsdeploy/yaml/yaml_translator.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Internal Jira WDT-474
Refine lists to reflect only deltas, including deletions, in change model.
Derive alias location and attribute name from change path.
Renamed some variables in compare_model._add_results() .
Allow more general model comments.
Use single aliases instance.
=> Allow target deletes for compareModel tool

core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Solves the original problem in #739 - deriving the versioned name for a library from its manifest for initial online deployment.
The issue of avoiding redeployment of a library (or application) when the versioned name matches an existing deployment is unresolved. There are complex issues with determining the versioned name during the strategy phase that will require additional changes.
=> Issue #739 library deploy manifest

core/src/main/java/oracle/weblogic/deploy/yaml/AbstractYamlTranslator.java, core/src/test/python/variable_injector_test.py
Example: WebAppFilesCaseInsensitive can have values of [false, os, true]
Internal Jira WDT-463
=> Don't capitalize true/false values when parsing model

core/src/main/python/wlsdeploy/json/json_translator.py
Resolves 14.1.1 compareModel unit test problems.
Make separate case for boolean text, no longer auto-converted with newer Jython.
Internal Jira WDT-486
=> Fix conversion problem in JSON translator

system-test/src/test/java/oracle/weblogic/deploy/integration/BaseTest.java, system-test/src/test/resources/build-archive.sh
Avoid generating under src directory, accidentally committing.
System test ran clean, archive is being referenced under target dir.
=> System test: generate the sample archive in the target/resources directory

core/src/main/java/oracle/weblogic/deploy/util/WLSDeployArchive.java, core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py, core/src/main/python/wlsdeploy/tool/deploy/applications_version_helper.py, core/src/main/python/wlsdeploy/tool/util/archive_helper.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Exploded shared libraries are working.
Extracted version checking into applications_version_helper.py .
Internal Jira WDT-482
=> Use versioned names for apps and libraries when planning and deploying

core/src/main/python/deploy.py, core/src/main/python/update.py, core/src/main/python/wlsdeploy/tool/deploy/deployer_utils.py
If no restarts are actually required (i.e. cluster is down) then:
1. don't write empty restart file
2. return a 0 return code that no restarts are required.
=> do not write empty restart file

core/src/main/python/compare_model.py, core/src/main/python/extract_resource.py, core/src/main/python/prepare_model.py, core/src/main/python/wlsdeploy/tool/validate/validator.py, core/src/main/python/wlsdeploy/util/model_context.py
Also allow compareModel in TOOL validate mode.
Jira WDT-487 (extractDomainResource)
Jira WDT-494 (prepareModel)
=> Allow missing archive for prepareModel, extractDomainResource

core/src/main/python/wlsdeploy/tool/util/target_helper.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
One off code to save off the original dynamic cluster size and restore after setservergroups resets the value \.
Would appreciate someone testing this.
=> Restore cluster dynamic size after setServerGroups reset value

core/src/main/python/compare_model.py
=> Compare model - use top-level attribute location to determine names

core/src/main/antlr4/oracle/weblogic/deploy/yaml/Yaml.g4
YAML validator confirms this is allowed, including the beginning of the name.
Quotes are allowed, not required.
Fixes #783 
Internal Jira WDT-514
=> Allow dollar sign in ID or value

core/pom.xml, core/src/main/python/discover.py, core/src/main/python/prepare_model.py, core/src/main/python/wlsdeploy/tool/util/targets/file_template_helper.py, core/src/main/python/wlsdeploy/util/target_configuration_helper.py, core/src/main/resources/oracle/weblogic/deploy/k8s/create_k8s_secrets.sh, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Use a template for generated script.
Internal Jira WDT-470
Sample output:
```
secret "very-very-long-domain-uid-weblogic-credentials" deleted
secret/very-very-long-domain-uid-weblogic-credentials created
secret/very-very-long-domain-uid-weblogic-credentials labeled
secret "very-very-long-domain-uid-jdbc-very-very-long-datasource-name-too-long-really" deleted
secret/very-very-long-domain-uid-jdbc-very-very-long-datasource-name-too-long-really created
secret/very-very-long-domain-uid-jdbc-very-very-long-datasource-name-too-long-really labeled
secret/very-very-long-domain-uid-jdbc-another-very-very-long-datasource-name created
secret/very-very-long-domain-uid-jdbc-another-very-very-long-datasource-name labeled
WARNING: These 2 secret names are too long to be mounted in a Kubernetes pod: …
```
=> Check for long secret names in generated script

core/src/main/python/wlsdeploy/tool/deploy/deployer_utils.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Assume that characters that cause a parsing error when doing a URI means the file is not in the archive but is a pattern file in the config.xml
Internal Jira WDT-519
Internal Jira WDT-521
=> Handle parsing exception on files with percent signs

core/src/main/python/wlsdeploy/json/json_translator.py
This results in some boolean fields becoming strings in the JSON model, but TypeUtils converts those correctly when the model is applied to the domain.
Internal JIRA WDT-532
=> JSON formatter - don't convert true / false strings to boolean

core/src/main/python/deploy.py, core/src/main/python/update.py, core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py, core/src/main/python/wlsdeploy/tool/deploy/deployer_utils.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Delete app/library targets during edit session for online.
Remove target deletion functionality from online app/library deployment.
Refactored restart checking into a shared method online_check_save_activate().
Tested with update and deploy tools.
Internal Jira WDT-534
=> WIP: Avoid undeploying apps and libraries when targets are deleted

core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/python/wlsdeploy/tool/deploy/topology_updater.py, core/src/main/python/wlsdeploy/tool/util/topology_helper.py, core/src/main/python/wlsdeploy/tool/validate/validation_utils.py
After setting server groups, just remove the deleted items.
WLST does not allow SSL/ListenPort to be set a second time.
Also fixed PyDictionary type match for new Jython version.
Fixes #819
=> Avoid re-deploying clusters and servers a second time

core/src/main/python/compare_model.py, core/src/main/python/wlsdeploy/aliases/alias_utils.py, core/src/main/python/wlsdeploy/tool/compare/__init__.py, core/src/main/python/wlsdeploy/tool/compare/model_comparer.py, core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py, core/src/main/python/wlsdeploy/tool/validate/validation_utils.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, core/src/test/python/compare_model_test.py, core/src/test/resources/compare/model-4-new.yaml, core/src/test/resources/compare/model-4-old.yaml
Keep the source path for applications and libraries in the change model, even if unchanged.
Internal Jira WDT-535
Avoid flagging non-named model folders for deletion in the change model.
Internal Jira WDT-527
ModelDiffer has been moved out of compare_model.py (see model_comparer.py).
Refactored as ModelComparer to use a single pass through the models, and provide additional checks.
Some messages in applications_deployer.py were corrected to indicate Application or Library as needed.
Fix in alias_utils.py for merging properties.
=> Compare tool: keep source path, don't delete non-name folders

core/src/main/python/wlsdeploy/tool/discover/discoverer.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Check the WLST isSet() method before adding each attribute to the model.
FYI wlst_helper.is_set() already checks for online, returns True for offline.
Fixes #825
Internal JIRA WDT-288
=> Avoid discovering attributes that are not set (online mode)

core/src/main/python/wlsdeploy/aliases/alias_entries.py, core/src/main/python/wlsdeploy/aliases/aliases.py, core/src/main/python/wlsdeploy/util/cla_utils.py, core/src/main/python/wlsdeploy/util/string_utils.py, core/src/main/python/wlsdeploy/util/weblogic_helper.py
Remove hard dependencies on Weblogic classes from WeblogicHelper in the aliases and alias_entries python files. This will allow the alias test to run without having a dependency on an oracle home.
=> remove WeblogicHelper dependencies from aliases for aliastest

pom.xml, system-test/pom.xml
With these changes, the process to cut a new release is:
1. Make sure that your local repo is in sync with origin/master and that the local repo is on the master branch (there can be no outstanding changes or commits on the master branch).
2. Run the following command just to ensure that the build and tests are succeeding:
```
mvn clean verify
```
3. Create a release.properties file in the root of the project with the following content
```
releaseVersion=<non-snapshost-version>
developmentVersion=<next-snapshot-version>
```
4. Run the following command:
```
mvn -B release:prepare release:perform
```
5. Create a new release in github based on the tag `release-<non-snapshot-version>` and upload the new installer from `~/.m2/repository/com/oracle/weblogic/lifecycle/weblogic-deploy-installer/< …
=> Fixing the release plugin

core/src/main/python/wlsdeploy/tool/util/targets/file_template_helper.py, core/src/main/targetconfigs/vz/application.yaml
Problems discussed in verrazzano-dev Slack:
- Section `clusters` should be omitted if list is empty.
- A control character was removed from application.yaml .
For template processing, skip template block if false value in hash.
Internal Jira WDT-522
=> For -target vz and wko, omit cluster section if list is empty

core/src/main/targetconfigs/vz/vz_filter.py, core/src/main/targetconfigs/wko/wko_operator_filter.py
These steps were creating ServerTemplate entries for each Cluster, causing problems with static clusters.
We were unable to determine a scenario where this behavior was desired, even with dynamic clusters.
Changed in wko and vz filters.
JIRA-WDT-541
=> Remove target filter steps to add server templates

core/src/main/java/oracle/weblogic/deploy/logging/SummaryHandler.java
Java is going to be removing support for `new <WrapperType>(<primitiveType>)`
=> Removed deprecated Integer constructor usage

ReleaseProcess.md, github-release.xml, installer/src/assembly/zip.xml, pom.xml, system-test/pom.xml
Details of the automated process can be found in the ReleaseProcess.md file at the root of the project.
=> Automating the release process

core/src/main/python/validate.py, core/src/main/python/wlsdeploy/util/cla_helper.py, core/src/test/python/validation_test.py, core/src/test/python/wlsdeploy/util/cla_helper_test.py, core/src/test/resources/model_filters.json, core/src/test/resources/wdt_mii_filter.py, core/src/test/resources/wdt_validate_filter.py
To support generating configuration overrides with model filtering , for Model-In-Image (MII) domain home source type, the following changes are needed in WDT:
1. Add the ability to apply filters for The Validate Model Tool (validateModel),
2. Persist model after filtering has been applied.
For MII, validateModel tool is used to generate merged models and filtering is needed to apply configuration overrides.
A couple unit tests created to verify that model filter(s) are invoked (for validateModel tool) and to verify that filter changes are persisted, if configured.
=> Filtering on validate

pom.xml
Adding configuration to the Maven release plugin so that it can pass the unit-test-wlst-dir system property from the command-line to the release builds without requiring the WLST_DIR environment variable (which will also still work).
=> Release plugin args

core/src/main/python/wlsdeploy/tool/create/domain_creator.py
Create LogFilter, XMLEntity Cache, and XML Registry earlier in the flow.  Server/Log depends on LogFilter.  Fixes #871
=> createDomain create LogFilter, XMLEntity Cache, and XML Registry earlier 

core/src/main/python/update.py
Move the change rcu password update logic before any offline update.
=> Fix rcu schema pwd update regression

core/src/main/python/wlsdeploy/tool/util/rcu_helper.py
This fixes the failure when updating a jrf domain's rcu password but at the same time adding a new datasource.
=> Fix -updateRCUSchemaPassword failed when it has new custom datasource

core/pom.xml, pom.xml
I was able to build with JDK 8, 11, and 16.  The generated classes are still compatible with JDK 1.7 based on the target and requirement to run with WLS 10.3.6.
=> Allow build with JDK11

core/src/test/resources/simple-demo-jms-full.yaml, core/src/test/resources/simple-demo-jms.yaml
- eliminate use of long deprecated 'session pool' and 'weighted dist dest' features
- ensure all destinations are targeted using 'subdeployments'.
=> minor jms sample change so it implicitly follows best practices

core/src/main/python/wlsdeploy/tool/util/rcu_helper.py
This fixes the issue when user specify rcu_prefix as lower case and when we use it to compare ds schema name actually used in the jdbc descriptor.
=> fix rcu_prefix case issue

documentation/1.9/content/userguide/target_env.md
WebLogic Kubernetes Target should be `wko`
=> Correct typo on Targets documentation

core/src/main/python/wlsdeploy/tool/extract/domain_resource_extractor.py
extractDomainResource should use the replica count when specified in the kubernetes section as the default cluster replicas count instead of the cluster size
=> if defined, use top-level replicas as default for clusters

documentation/1.9/content/userguide/target_env.md
The domain resource filename for discoverDomain and prepareModel when using -target vz or -target wko has changed to vz-application.yaml and wko-domain.yaml, respectively.
=> update documentation for -target output filenames

core/src/main/python/discover.py, core/src/main/python/wlsdeploy/tool/util/variable_injector.py, core/src/main/python/wlsdeploy/util/target_configuration_helper.py, core/src/main/python/wlsdeploy/util/variables.py
Fix when no -variable_file is supplied in target discovery, nothing is generated
=> Fix target file generation regression

core/src/main/java/oracle/weblogic/deploy/util/PyOrderedDict.java, core/src/main/python/wlsdeploy/yaml/yaml_translator.py
The target filters set ServerTemplate / AutoMigrationEnabled to False.
Any custom filter could do the same.
Tested backward compatibility with 12.2.1.3.
Internal JIRA-WDT-564
=> Allow Jython bool value in model for deep copy and file write in WLS 14.1.2

core/src/main/python/wlsdeploy/tool/util/target_helper.py
This was found by 10.3.6 customer and internal rep. No issue or Jira was created.
The call to applyJRF had an invalid variable making the applyJRF call fail.
=> Bug found in call to applyJRF for 11g

alias-test/src/test/python/aliastest/generate/generator_helper.py, alias-test/src/test/python/aliastest/util/all_utils.py, alias-test/src/test/python/aliastest/verify/verifier_helper.py, core/src/main/java/oracle/weblogic/deploy/create/RCURunner.java, core/src/main/java/oracle/weblogic/deploy/util/FileUtils.java, core/src/main/java/oracle/weblogic/deploy/util/PyOrderedDict.java, core/src/main/java/oracle/weblogic/deploy/util/WLSDeployZipFile.java, core/src/main/python/wlsdeploy/aliases/location_context.py, core/src/main/python/wlsdeploy/aliases/password_utils.py, core/src/main/python/wlsdeploy/json/json_translator.py, core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/python/wlsdeploy/tool/create/security_provider_creator.py, core/src/main/python/wlsdeploy/tool/modelhelp/model_kubernetes_printer.py, core/src/main/python/wlsdeploy/tool/modelhelp/model_sample_printer.py, core/src/main/python/wlsdeploy/tool/util/target_helper.py, core/src/main/python/wlsdeploy/util/model_context.py, core/src/test/python/validation_test.py, core/src/test/python/wlsdeploy/util/cla_helper_test.py, documentation/1.9/content/concepts/model.md, documentation/1.9/themes/hugo-theme-learn/static/js/learn.js
fix typo grammar spelling, and replace with to correct word with reference from [Merriam webster](https://www.merriam-webster.com/)
=> fix: typo grammar spell

core/src/main/python/wlsdeploy/tool/compare/model_comparer.py, core/src/test/python/compare_model_test.py
We need to return all original unchanged attributes for Application and Library also,  the reason is the delta can be used for updating the domain which can triggers undeploy and deploy again,  without the original values, then after the undeploy, the model used will not have enough information for deploy again.
=> Wdt 575 - compareModel needs to return all original unchanged attributes for app/lib

core/src/main/java/oracle/weblogic/deploy/util/WLSDeployArchive.java, core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/python/wlsdeploy/tool/deploy/topology_updater.py, core/src/main/python/wlsdeploy/tool/util/archive_helper.py, core/src/main/python/wlsdeploy/tool/util/library_helper.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Fixes #944 
User can create a folder in the archive to store files. These files will be extracted into the domain.
=> Extract files from user custom folder in archive

core/src/main/python/wlsdeploy/tool/create/creator.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Fixes #990 
If a empty singleton folder (no attributes or subfolders) is presented in the model, add that folder to the domain.
=> Add empty model folders to domain

installer/src/main/bin/shared.sh
${@:2} is a bash array usage and not supported in all Bourne implementations.
=> Remove usage of array in shared.sh

documentation/1.9/content/concepts/archive.md, installer/src/main/lib/injectors/url.json
Fixes Jira WDT-569
Add WTC and Jolt url to url.json for variable injection
=> Wdt 569 jolt wtc url injectors

core/src/main/python/wlsdeploy/tool/validate/validator.py
Adding code that prevents stack traces when the user sets a "artificial folder" value to null instead of an object in 14.1.1+.  
Note:  The JSON parser will still fail when encountering `null` for WLS versions prior to 14.1.1 due to a bug in the Jython 2.2.1 implementation of dictionary and/or `Py.None` (Jython 2.2.1 uses a `java.util.Hashtable` to store the dictionary, `Py.None` maps to `null`, and `java.util.Hashtable` does not support `null` values so there is no way to store `Py.None` in a dictionary without `java.util.Hashtable.put()` generating a `NullPointerException`).
=> adding check for null attributes dictionary

core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/python/wlsdeploy/tool/util/default_authenticator_helper.py
Fixes Issue #1010 
Security user password that was encrypted using the encryption tool was not decrypted before being decrypted for the security files.
=> decrypt encyrpted security user password before encrypting for security

core/src/main/python/wlsdeploy/util/variables.py
This PR is to support token substitution using a k8s secret where the key value is an empty string.
=> Support token substitution using empty string in k8s secret

core/src/main/python/compare_model.py, core/src/main/python/discover.py, core/src/main/python/extract_resource.py, core/src/main/python/prepare_model.py, core/src/main/python/validate.py, core/src/main/python/wlsdeploy/tool/prepare/model_preparer.py, core/src/main/python/wlsdeploy/tool/validate/kubernetes_validator.py, core/src/main/python/wlsdeploy/tool/validate/validator.py, core/src/main/python/wlsdeploy/util/cla_utils.py, core/src/main/python/wlsdeploy/util/model_context.py, core/src/main/python/wlsdeploy/util/target_configuration.py, core/src/main/python/wlsdeploy/util/validate_configuration.py, core/src/main/python/wlsdeploy/util/variables.py, core/src/main/python/wlsdeploy/util/weblogic_helper.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, system-test/src/test/java/oracle/weblogic/deploy/integration/ITWdt.java
New mode `wktui` will match `strict`, but allow unresolved secret, environment, and file tokens.
In standalone `validateModel`, list warning and severe messages in summary, without stopping validation.
Standalone `validateModel` in `strict` mode will now flag missing archive entries as errors, and return exit code 2.
See internal Jira WKTUI-215
Use `ValidateConfiguration` to check validation mode.
Some message keys were renumbered.
=> Create validation mode for WKTUI

core/src/main/python/wlsdeploy/tool/util/filter_helper.py, core/src/main/python/wlsdeploy/util/cla_utils.py, core/src/main/python/wlsdeploy/util/target_configuration.py
Allow newer WKT UI to work with pre-2.0 WDT.
Allow validateModel with method `wktui` (interpret as `lax`).
Allow target configurations with validate method `wktui` (`lax`) and ID filter `wko_filter` (no-op).
=> Allow WDT 2.0 target configuration with reduced functionality

core/src/main/python/wlsdeploy/aliases/aliases.py, core/src/main/python/wlsdeploy/util/model_context.py, core/src/main/python/wlsdeploy/util/path_utils.py
Split discovered classpath attributes correctly to tokenize path elements.
Substitute classpath attributes correctly before setting in WLST.
Fixes #1025
=> Discover large classpath attribute values

core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py
Fixes #975.  The application deployer was not updating its existing names list after deleting an application.  If the same application name in the model was being re-added, create_if_not_exists thinks the application is still there.
=> fixed issue where deleted application was still thought to exist 

core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/python/wlsdeploy/tool/deploy/topology_updater.py, core/src/main/python/wlsdeploy/tool/util/attribute_setter.py, core/src/main/python/wlsdeploy/tool/util/topology_helper.py, core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/Server.json
Also, add set method to Server/SSL/ListenPort to enable SSL while setting attribute.
Fixes #983
=> Re-deploy servers and clusters after initial domain creation

core/src/main/python/wlsdeploy/tool/util/filter_helper.py, core/src/main/python/wlsdeploy/tool/util/filters/model_traverse.py, core/src/main/targetconfigs/k8s/k8s_operator_filter.py, core/src/main/targetconfigs/k8s/target.json, core/src/main/targetconfigs/vz/target.json
Also fixed bugs with k8s filter:
- Remove server template creation from k8s filter (see PR #844).
- Skip version-invalid folders when running online attribute filter.
=> Add separate target filters for k8s and vz

documentation/2.0/content/userguide/tools/kubernetes.md
Replace "named object list" with hyphenated object list in examples, remove description
=> Update extractResource/kubernetes documentation

alias-test/src/test/python/aliastest/verify/verifier_helper.py, core/src/main/python/wlsdeploy/aliases/aliases.py
when checking default value, the default is None. Aliases is trying to do an iterate over the parts of a path without checking if it is None first. Need this for the alias tests.
=> Do not look for path tokens if path is None

core/pom.xml, installer/pom.xml, pom.xml
I have verified that this resolves the build number plugin error that was occurring during the release process, forcing us to rebuild the binaries after the release process.
=> switching to new jgit build number plugin to address error during release process

core/src/main/java/oracle/weblogic/deploy/util/CommentMap.java, core/src/main/java/oracle/weblogic/deploy/util/OrderedMap.java, core/src/main/java/oracle/weblogic/deploy/util/PyOrderedDict.java, core/src/main/java/oracle/weblogic/deploy/yaml/AbstractYamlTranslator.java, core/src/main/java/oracle/weblogic/deploy/yaml/YamlRepresenter.java, core/src/main/python/wlsdeploy/json/json_translator.py, core/src/main/python/wlsdeploy/tool/compare/model_comparer.py, core/src/main/python/wlsdeploy/yaml/yaml_translator.py
Restore comments in compareModel output.
=> Allow comment in YAML output files

documentation/2.0/content/userguide/target_env.md
Re-organize and add secret credentials information.
Internal Jira WDT-507
=> Target environment doc changes

core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/DomainInfo.json, documentation/2.0/content/userguide/tools/compare.md, documentation/2.0/content/userguide/tools/create.md, documentation/2.0/content/userguide/tools/deploy.md, documentation/2.0/content/userguide/tools/discover.md, documentation/2.0/content/userguide/tools/encrypt.md, documentation/2.0/content/userguide/tools/kubernetes.md, documentation/2.0/content/userguide/tools/model_help.md, documentation/2.0/content/userguide/tools/prepare.md, documentation/2.0/content/userguide/tools/update.md, documentation/2.0/content/userguide/tools/validate.md, documentation/2.0/content/userguide/tools/variable_injection.md, installer/src/main/bin/deployApps.cmd
=> Add parameter tables to 2.0 documentation

documentation/2.0/content/userguide/tools/compare.md, documentation/2.0/content/userguide/tools/create.md, documentation/2.0/content/userguide/tools/deploy.md, documentation/2.0/content/userguide/tools/discover.md, documentation/2.0/content/userguide/tools/encrypt.md, documentation/2.0/content/userguide/tools/kubernetes.md, documentation/2.0/content/userguide/tools/model_help.md, documentation/2.0/content/userguide/tools/prepare.md, documentation/2.0/content/userguide/tools/update.md, documentation/2.0/content/userguide/tools/validate.md, documentation/2.0/content/userguide/tools/variable_injection.md
According to Oracle style guidelines, "Use of the Monospace Font for in-text code elements: Use monospace/code font for names of arguments, attributes, classes, commands/statements, directories, fields, files, methods, modules, nodes, packages, parameters, properties, roles, and schemas, as well as values."
=> apply code font where needed

documentation/2.0/content/concepts/archive.md, documentation/2.0/content/developer/alias-definitions.md
=> add edits from Derek

system-test/src/test/java/oracle/weblogic/deploy/integration/BaseTest.java
IT tests are stepping on each other's database when running on the same host.
=> give each IT run its own database container in case two builds run on the same machine

core/src/main/python/wlsdeploy/tool/create/security_provider_creator.py
fixes Jira 608
Changing adjudicator in versions 12.2.1.3 and below encounters a WLST problem with the xsi type in the config.xml. Have opened  WLST bug 33847230. put changes in to handle version specific problems with the adjudicator.
=> Wdt 608 undo adjudicator code

documentation/2.0/content/userguide/target_env.md
Added `use_persistent_volume` for target configuration file.
Changed location of resource file templates.
Use "Kubernetes resource file" for Verrazzano and general case.
=> Documentation changes for target type changes

core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/JDBCSystemResource.json
Tested with different JDBCSystemResources and JDBCResource folder names.
Internal Jira WDT-615
=> Use JDBCResource name for flattened folder in JDBCDriverParams Properties

documentation/2.0/content/developer/project-structure.md
The sample folder was removed from the source structure but the reference in the documentation was still there.
=> remove reference to samples folder in project structure doc

core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/WebserviceSecurity.json
WebserviceSecurity.json had a boolean value as default for a password field.
=> Fix WebserviceSecurity

core/src/main/java/oracle/weblogic/deploy/json/JsonStreamTranslator.java, system-test/src/test/java/oracle/weblogic/deploy/integration/ITWdt.java
Remove public identifiers from test methods no longer required for JUnit5, and recommended by static code check.
=> remove public identifiers from test methods per JUnit5

core/src/main/python/wlsdeploy/tool/discover/custom_folder_helper.py, core/src/main/python/wlsdeploy/tool/util/mbean_utils.py
14.1.1 used to return str version of setter and getter return type stripped of constant <type ', no longer does so strip it off manually
=> compensate for change in 14.1.1 mbean interface

core/pom.xml, pom.xml
Allow the build to generate code coverage reports without having to run the verify step.
=> Run code coverage during test phase, but after all other plugins complete

core/src/main/typedefs/JRF-Compact.json, core/src/main/typedefs/JRF.json
Add JRF schema component WLS to typedefs, I think the scheme is added in 12.2.1 and above for BI?  ATP has  different default table space than regular oracle database.  If the WLS component is not specified in the typedefs for JRF,  then rcu automatically creates the component but with the regular db default table space name internally and results in ORA-01031: insufficient privileges.  This change will force the component in the command line with the correct  tablespace for ATP.
=> Fixed missing WLS schema component causing ATP rcu creation failure

core/src/main/python/extract_resource.py, core/src/main/python/wlsdeploy/tool/util/targets/additional_output_helper.py, core/src/main/python/wlsdeploy/util/cla_utils.py, core/src/main/python/wlsdeploy/util/target_configuration.py, core/src/main/targetconfigs/templates/vz-application.yaml, core/src/main/targetconfigs/templates/wko-domain.yaml, core/src/main/targetconfigs/vz-dii/target.json, core/src/main/targetconfigs/vz-pv/target.json, core/src/main/targetconfigs/vz/target.json, core/src/main/targetconfigs/wko-dii/target.json, core/src/main/targetconfigs/wko-pv/target.json, core/src/main/targetconfigs/wko/target.json
Hide the spec / configuration / model section unless the domain source type is model-in-image.
Move target configuration validation to target_configuration.py .
Assign default extract target type before processing arguments.
Internal JIRA WDT-613
=> Set domain type in domain resource templates

core/src/main/python/wlsdeploy/aliases/alias_constants.py
Offline discover was failing for a domain with this provider.
Partial fix for the offline discovery mentioned in #1126 .
=> Corrected alias name lookup for OracleIdentityCloudIntegrator

core/src/main/python/wlsdeploy/tool/util/filters/wko_filter.py, core/src/test/python/wlsdeploy/tool/util/filters/wko_filter_test.py, core/src/test/resources/prepare/wko-filter.yaml
Confirmed that references in server are already being removed.
Internal Jira WDT-614
=> Remove machine references from server templates in model filter

core/src/main/python/discover.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Don't allow -archive_file to be specified with -remote or -skip_archive.
Remove duplicate invalid report section.
Interrnal Jira WDT-646 
Sample output file content:
```
{
"missingArchiveEntries" : [
{
"sourceFile" : "wlsdeploy/sharedLibraries/sample_lib.jar",
"type" : "SHARED_LIBRARIES",
"path" : "wlsdeploy/sharedLibraries/sample_lib.jar"
},
{
"sourceFile" : "wlsdeploy/applications/sample_war.war",
"type" : "APPLICATIONS",
"path" : "C:/tmp/archives/wlsdeploy/applications/sample_war.war"
}
]
}
```
=> Write missing archive entries from discover to a results file if configured

core/src/main/python/wlsdeploy/tool/discover/common_resources_discoverer.py, core/src/main/python/wlsdeploy/tool/discover/discoverer.py
Fixes Jira 653 for discovery using -remote. Make sure that the file system paths generated for the remote report are not relative to the domain, but make them absolute paths with forward slashes.
fix a missing place for doing -remote file system paths
=> for remote make sure file system path is absolute

core/src/main/python/wlsdeploy/tool/util/targets/output_file_helper.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, core/src/main/targetconfigs/templates/wko-domain.yaml
Add a comment if there are no image pull secrets in the resulting resource file
=> Remove default image pull secret from WKO domain resource template

core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
This PR fixes regression for 1144 (stop application with no target in online update domain) and 937 which failed if the source path is absolute path.  It also causes regression wko online update untargeting applications.
=> Fix deletetarget and nontargetupdate

core/src/main/python/compare_model.py, core/src/main/python/create.py, core/src/main/python/deploy.py, core/src/main/python/discover.py, core/src/main/python/encrypt.py, core/src/main/python/extract_resource.py, core/src/main/python/model_help.py, core/src/main/python/prepare_model.py, core/src/main/python/update.py, core/src/main/python/validate.py, core/src/main/python/variable_inject.py, core/src/main/python/wlsdeploy/exception/exception_helper.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Created a try/except around mains of discover.py, create.py, etc.  to deal with unanticipated exceptions.  Inform user of the issue, and request they create an issue, attaching the log and standard output.  Two different messages are created, one for the user without a stack trace, and one for the log with a stack trace.
=> JIRA WDT-638 - Should never exit with uncaught exceptions

core/src/main/python/compare_model.py, core/src/main/python/create.py, core/src/main/python/deploy.py, core/src/main/python/discover.py, core/src/main/python/encrypt.py, core/src/main/python/extract_resource.py, core/src/main/python/model_help.py, core/src/main/python/prepare_model.py, core/src/main/python/update.py, core/src/main/python/validate.py, core/src/main/python/variable_inject.py, core/src/main/python/wlsdeploy/exception/exception_helper.py, core/src/main/python/wlsdeploy/tool/create/domain_typedef.py, core/src/main/python/wlsdeploy/tool/deploy/deployer_utils.py, core/src/main/python/wlsdeploy/tool/modelhelp/model_help_printer.py, core/src/main/python/wlsdeploy/tool/modelhelp/model_kubernetes_printer.py, core/src/main/python/wlsdeploy/tool/modelhelp/model_sample_printer.py, core/src/main/python/wlsdeploy/tool/util/archive_helper.py, core/src/main/python/wlsdeploy/util/cla_helper.py, core/src/main/python/wlsdeploy/util/cla_utils.py, core/src/main/python/wlsdeploy/util/exit_code.py, core/src/main/python/wlsdeploy/util/target_configuration_helper.py
Removing circular imports from and to CommandLineArgUtil.  Exit code constants moved out of CommandLineArgUtil and into simple class, ExitCode.
=> refactor exit codes to prevent circular imports for CommandLineArgUtil

core/src/main/python/compare_model.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
This PR cleanup CLAExceptions and exit code logic
=> WDT-659 cleanup CLAException for compare_model.py

core/src/main/java/oracle/weblogic/deploy/util/XPathUtil.java, core/src/main/python/wlsdeploy/util/model_context.py
Moved message to FINE, instead of INFO, and changed the wording from:
####<Jul 27, 2022 3:07:04 PM> <INFO> <XPathUtil> <getPSU> <> <No patches home at .../Oracle/Middleware14.1.1.0.0/inventory/patches>
Only when a PSU was found would the following message be printed:
####<Jul 27, 2022 10:24:14 PM> <INFO> <ModelContext> <__copy_from_args> <WLSDPLY-01050> <WebLogic version for aliases is 12.2.1.4.0.220105>
Changed to print the message whether a PSU was found or not:
####<Jul 27, 2022 10:26:38 PM> <INFO> <ModelContext> <__copy_from_args> <WLSDPLY-01050> <WebLogic version for aliases is 12.2.1.4.0>
=> removed message when no PSU was found

pom.xml
With valid YAML, SnakeYaml 1.29 has trouble parsing YAML with tabs at the end of lines, and empty lines between comment lines.
WDT symptom:
1. WLSDPLY-09014: createDomain was unable to load the model from test.yaml due to a translation error: Unable to parse model from file test.yaml : Failed to parse file test.yaml: -1
Stacktrace from log:
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:136)
at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1222)
at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:308)
at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248)
=> Update SnakeYaml to 1.30 to fix YAML parsing bug

core/src/main/python/compare_model.py, core/src/main/python/create.py, core/src/main/python/deploy.py, core/src/main/python/discover.py, core/src/main/python/encrypt.py, core/src/main/python/extract_resource.py, core/src/main/python/model_help.py, core/src/main/python/prepare_model.py, core/src/main/python/update.py, core/src/main/python/validate.py, core/src/main/python/variable_inject.py, core/src/main/python/wlsdeploy/exception/exception_helper.py, core/src/main/python/wlsdeploy/util/tool_exit.py
I tried to ensure wherever there was a call to logger.entering() that there was a matching logger.exiting().  Also, all tool exits should now be handled consistently, using either _tool_exit.__log_and_exit() to do a logger.exiting() and tool_exit.end() if there was a __logger.entering() or simply tool_exit.end() if not.
Also, removed duplicate code in multiple except blocks, setting an exit code, and after the except blocks, cleaning up temp files and exiting with whatever exit code was set.
=> WDT-639 consistent exit handling across tools

core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/UnixMachine.json
Fixes WDT-661
The wlst_type was not set correctly for online.
=> WDT-661 Delete Machines instead of UnixMachines in online

core/src/main/python/wlsdeploy/tool/discover/domain_info_discoverer.py
Fixes #1183 
Domain bin libraries collected without checking for skip_archive and remote
=> Put skip archive and remote test into domain bin scripts

core/src/main/python/create.py
Found an issue in create.py while testing and discovered the missing method name and the wrong exit code is used during domain creation
=> Fixed exit code and missing method name when error occurs

core/src/main/python/wlsdeploy/tool/create/atp_helper.py, core/src/test/python/atp_helper_test.py
Revised the logic to handle multiple addresses (description) in the URL and added a unit test.
=> Wdt 677 - atp_helper  not handling multiple descriptions for ATP DG url case

integration-tests/alias-test/generate/src/test/python/aliastest/generate/generator_online.py
AppDeployments and Libraries are marked single instead of multiple in online generated files. fix this
=> mark single as multiple for special cases

integration-tests/alias-test/verify/src/test/python/aliastest/verify/verifier.py
If the wlst value is delimited type and alias is string or list is a correct combination.
=> delimited type in wlst matches string in alias

integration-tests/alias-test/verify/src/test/python/aliastest/verify/verifier.py
verify is not using the wlst value, so by changing to the wlst_attribute_name, will not go through code for JARRAY find mbean Class
=> switch to wlst_attribute_name method

integration-tests/alias-test/generate/src/test/python/aliastest/generate/generator_base.py
get with returned byte[] as a type should be changed to password if cmo type is password.
=> change byte array to password

integration-tests/alias-test/generate/src/test/python/aliastest/generate/generator_base.py, integration-tests/alias-test/generate/src/test/python/aliastest/generate/mbean_info_helper.py
attribute exists now gets derived_default = False while attribute does not exists does not get a derived default value.
=> Return false for derived default false

core/src/main/java/oracle/weblogic/deploy/logging/SummaryHandler.java, core/src/main/java/oracle/weblogic/deploy/util/XPathUtil.java, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
=> filtering non-WDT messages from being published by the Summary Handler

core/src/main/python/deploy.py, core/src/main/python/update.py, core/src/main/python/wlsdeploy/util/cla_utils.py, core/src/main/python/wlsdeploy/util/model_context.py
=> removing remnants of unused -prev_model_file argument

core/src/main/python/extract_resource.py, core/src/main/python/wlsdeploy/tool/util/targets/additional_output_helper.py, core/src/main/python/wlsdeploy/util/cla_utils.py, core/src/main/python/wlsdeploy/util/model_context.py, core/src/test/python/wlsdeploy/tool/extract/extract_test.py
=> removing deprecated -domain_resource_file argument

core/src/main/python/extract_resource.py, installer/src/main/bin/extractDomainResource.cmd, installer/src/main/bin/extractDomainResource.sh
Fixes Jira WDT-708
-archive_file is not longer needed because it does not contain the model
=> Remove archive_file argument from extractDomainResource

core/src/main/python/wlsdeploy/tool/create/atp_helper.py, core/src/test/python/atp_helper_test.py
This PR fixes the new ATP wallet URL format in tnsnames.ora file causing connection problems when creating a JRF domain.
=> Fix for new atp format without server dn entries

documentation/3.0/content/userguide/database/connect-db.md, documentation/3.0/content/userguide/tools/create.md
Create new section and move RCU doc into it.
=> Move RCU doc

core/src/main/java/oracle/weblogic/deploy/create/RCURunner.java, core/src/main/python/wlsdeploy/tool/create/atp_helper.py, core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/python/wlsdeploy/tool/create/rcudbinfo_helper.py, core/src/main/python/wlsdeploy/tool/create/ssl_helper.py
This fixes -run_rcu against SSL database and various refactoring of both ATP and SSL JRF database domain creation.
=> various atp and ssl JRF database refactoring

core/src/main/python/wlsdeploy/tool/discover/coherence_resources_discoverer.py
This PR fixes discovery error where the custom config file is set to coherenece/<cluster>/<file name> but the actual file is under $domain/config/coherence<cluster>/<file name> location.
=> Fix discovery error for custom config

core/src/main/python/wlsdeploy/tool/util/targets/additional_output_helper.py, core/src/main/python/wlsdeploy/tool/util/targets/crd_file_updater.py, core/src/main/python/wlsdeploy/tool/util/targets/model_crd_helper.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, core/src/main/targetconfigs/templates/vz-application-v1.yaml, core/src/test/python/wlsdeploy/tool/extract/extract_test.py, core/src/test/resources/extract/model-3.yaml
Add example comments for application rule paths.
Enable overrides from `verrazzano` model section.
Fixes internal Jira WDT-696
=> Update Verrazzano CRD ingress traits with application information

core/src/main/java/oracle/weblogic/deploy/util/XPathUtil.java, core/src/main/python/wlsdeploy/util/model_context.py
=> preventing the misleading log entry from being written at startup

core/src/main/python/create.py, core/src/main/python/discover.py, core/src/main/python/wlsdeploy/tool/prepare/model_preparer.py, core/src/main/python/wlsdeploy/tool/util/filter_helper.py, core/src/main/python/wlsdeploy/tool/util/filters/wko_filter.py, core/src/main/python/wlsdeploy/tool/util/filters/wko_final_filter.py, core/src/main/python/wlsdeploy/tool/validate/content_validator.py, core/src/main/python/wlsdeploy/tool/validate/validator.py, core/src/main/python/wlsdeploy/util/target_configuration.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties, core/src/main/targetconfigs/k8s/target.json, core/src/main/targetconfigs/vz-dii/target.json, core/src/main/targetconfigs/vz-pv/target.json, core/src/main/targetconfigs/vz/target.json, core/src/main/targetconfigs/wko-dii/target.json, core/src/main/targetconfigs/wko-pv/target.json, core/src/main/targetconfigs/wko/target.json, core/src/main/targetconfigs/wko4-dii/target.json, core/src/main/targetconfigs/wko4-pv/target.json, core/src/main/targetconfigs/wko4/target.json, core/src/test/python/wlsdeploy/tool/util/filters/wko_filter_test.py
- For create and prepare, check server template assignments, regardless of target.
- For discover and prepare with `wko` targets, check dynamic cluster server name prefixes. Add default values for missing prefixes, issue a warning for duplicate prefixes.
- For discover and prepare with `wko` version 3 targets, check admin server name and definition. Add default admin server name is missing, add empty definition with derived name if missing.
- Corrections to prepare model are applied to the last (or only) model in the list.
=> Perform final filtering on full, merged model

core/src/main/python/wlsdeploy/tool/discover/common_resources_discoverer.py
This changed when the alias was fixed to convert properties to a dictionary.
Tested with offline/online discover, with and without variables file.
Fixes #1415
=> Treat mail session properties as a dictionary during discover

core/src/main/python/wlsdeploy/tool/deploy/applications_deployer.py
=> Remove trailing slash from source path before extracting from archive

core/src/main/python/create.py, core/src/main/python/wlsdeploy/tool/create/domain_creator.py, core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
Added a step early in domain creation to verify database connectivity
=> Owls 741 verify jfr db connectivity

core/src/main/python/wlsdeploy/tool/create/domain_creator.py
=> Delete machines once, after templates are loaded
